# Auto-generated by shroudb-codegen. Do not edit.

from __future__ import annotations

import json
import urllib.request
import urllib.error
from typing import Any

from ._interface import Transport
from ..errors import ShrouDBError


class HttpTransport(Transport):
    """HTTP transport for Moat gateway connections.

    Commands are POSTed to ``/v1/{engine}`` as ``{"args": [...]}``.
    Uses ``urllib.request`` so the SDK has zero external dependencies.
    """

    def __init__(
        self,
        base_url: str,
        token: str | None = None,
        prefixes: dict[str, str] | None = None,
    ) -> None:
        self._base_url = base_url.rstrip("/")
        self._token = token
        self._prefixes = prefixes or {}

    async def execute(self, engine: str, args: list[str]) -> dict[str, Any]:
        prefix = self._prefixes.get(engine, f"/v1/{engine}")
        url = f"{self._base_url}{prefix}"

        headers: dict[str, str] = {"Content-Type": "application/json"}
        if self._token:
            headers["Authorization"] = f"Bearer {self._token}"

        body = json.dumps({"args": args}).encode("utf-8")
        req = urllib.request.Request(url, data=body, headers=headers, method="POST")

        try:
            with urllib.request.urlopen(req) as resp:
                data = resp.read().decode("utf-8")
                return json.loads(data)  # type: ignore[no-any-return]
        except urllib.error.HTTPError as exc:
            text = exc.read().decode("utf-8") if exc.fp else ""
            code = "INTERNAL"
            detail = text
            try:
                parsed = json.loads(text)
                if "error" in parsed:
                    parts = parsed["error"].split(" ", 1)
                    code = parts[0]
                    detail = parts[1] if len(parts) > 1 else parsed["error"]
            except (json.JSONDecodeError, ValueError):
                pass
            raise ShrouDBError(code, detail) from exc

    async def close(self) -> None:
        # HTTP is stateless — nothing to close.
        pass
