# Auto-generated by shroudb-codegen. Do not edit.

from __future__ import annotations

import abc
from typing import Any


class Transport(abc.ABC):
    """Transport abstraction for ShrouDB engine communication."""

    @abc.abstractmethod
    async def execute(self, engine: str, args: list[str]) -> dict[str, Any]:
        """Execute a command and return the parsed response."""

    @abc.abstractmethod
    async def close(self) -> None:
        """Close all connections."""
