# Auto-generated by shroudb-codegen. Do not edit.

from __future__ import annotations

import asyncio
import json
import re
import ssl as _ssl
from typing import Any

from ._interface import Transport


# Type alias for RESP3 wire values.
WireValue = str | int | None | list[Any] | dict[str, Any]


def _parse_uri(uri: str) -> dict[str, Any]:
    """Parse a RESP3 URI into connection parameters."""
    m = re.match(
        r"^([\w-]+)(\+tls)?://(?:([^@]+)@)?([^:/]+)(?::(\d+))?(?:/(.+))?$", uri
    )
    if not m:
        raise ValueError(f"Invalid ShrouDB URI: {uri}")
    return {
        "host": m.group(4),
        "port": int(m.group(5)) if m.group(5) else 6399,
        "tls": m.group(2) == "+tls",
        "token": m.group(3) or None,
        "keyspace": m.group(6) or None,
    }


class Resp3Connection:
    """A single RESP3 connection using asyncio streams."""

    def __init__(
        self,
        reader: asyncio.StreamReader,
        writer: asyncio.StreamWriter,
    ) -> None:
        self._reader = reader
        self._writer = writer

    @classmethod
    async def open(
        cls, host: str, port: int, tls: bool
    ) -> Resp3Connection:
        ssl_ctx: _ssl.SSLContext | None = None
        if tls:
            ssl_ctx = _ssl.create_default_context()
        reader, writer = await asyncio.open_connection(host, port, ssl=ssl_ctx)
        return cls(reader, writer)

    async def execute(self, *args: str) -> WireValue:
        """Send a RESP3 command and read the response."""
        self._send_raw(list(args))
        await self._writer.drain()
        return await self._read_frame()

    async def execute_pipeline_frame(
        self,
        prefix: list[str],
        commands: list[list[str]],
        request_id: str | None,
    ) -> WireValue:
        """Send a server-side PIPELINE frame (nested sub-command arrays)."""
        # *N\r\n
        # $<..>\r\n<prefix bulk strings>
        # [$10\r\nREQUEST_ID\r\n $<len>\r\n<id>\r\n]  (optional)
        # *M\r\n <sub-command bulk strings> ...       (x N commands)
        keyword_count = 2 if request_id is not None else 0
        outer_len = len(prefix) + keyword_count + len(commands)
        parts: list[str] = [f"*{outer_len}\r\n"]
        for p in prefix:
            encoded = p.encode("utf-8")
            parts.append(f"${len(encoded)}\r\n{p}\r\n")
        if request_id is not None:
            parts.append("$10\r\nREQUEST_ID\r\n")
            id_encoded = request_id.encode("utf-8")
            parts.append(f"${len(id_encoded)}\r\n{request_id}\r\n")
        for sub in commands:
            parts.append(f"*{len(sub)}\r\n")
            for arg in sub:
                encoded = arg.encode("utf-8")
                parts.append(f"${len(encoded)}\r\n{arg}\r\n")
        self._writer.write("".join(parts).encode("utf-8"))
        await self._writer.drain()
        return await self._read_frame()

    def close(self) -> None:
        self._writer.close()

    async def wait_closed(self) -> None:
        try:
            await self._writer.wait_closed()
        except (ConnectionError, BrokenPipeError):
            pass

    def _send_raw(self, args: list[str]) -> None:
        parts = [f"*{len(args)}\r\n"]
        for arg in args:
            encoded = arg.encode("utf-8")
            parts.append(f"${len(encoded)}\r\n")
            parts.append(arg)
            parts.append("\r\n")
        self._writer.write("".join(parts).encode("utf-8"))

    async def _read_line(self) -> str:
        line = await self._reader.readline()
        if not line:
            raise ConnectionError("Connection closed by server")
        return line.decode("utf-8").rstrip("\r\n")

    async def _read_frame(self) -> WireValue:
        line = await self._read_line()
        tag = line[0]
        payload = line[1:]

        if tag == "+":
            return payload
        if tag == "-":
            from ..errors import ShrouDBError

            space_idx = payload.find(" ")
            if space_idx >= 0:
                code = payload[:space_idx]
                detail = payload[space_idx + 1 :]
            else:
                code = payload
                detail = ""
            # Engines send "ERR {msg}" — infer structured code from message.
            if code == "ERR":
                code = _infer_error_code(detail)
            raise ShrouDBError(code, detail)
        if tag == ":":
            return int(payload)
        if tag == "$":
            length = int(payload)
            if length < 0:
                return None
            data = await self._reader.readexactly(length + 2)
            return data[:length].decode("utf-8")
        if tag == "*":
            count = int(payload)
            if count < 0:
                return None
            items: list[WireValue] = []
            for _ in range(count):
                items.append(await self._read_frame())
            return items
        if tag == "%":
            count = int(payload)
            result: dict[str, WireValue] = {}
            for _ in range(count):
                key = await self._read_frame()
                val = await self._read_frame()
                result[str(key)] = val
            return result
        return payload


class ConnectionPool:
    """Connection pool for a single RESP3 endpoint."""

    def __init__(
        self,
        host: str,
        port: int,
        tls: bool,
        max_connections: int = 10,
        token: str | None = None,
    ) -> None:
        self._host = host
        self._port = port
        self._tls = tls
        self._max_connections = max_connections
        self._token = token
        self._idle: list[Resp3Connection] = []
        self._active = 0
        self._waiters: list[asyncio.Future[Resp3Connection]] = []

    async def acquire(self) -> Resp3Connection:
        if self._idle:
            conn = self._idle.pop()
            self._active += 1
            return conn
        if self._active < self._max_connections:
            self._active += 1
            conn = await Resp3Connection.open(self._host, self._port, self._tls)
            if self._token:
                await conn.execute("AUTH", self._token)
            return conn
        loop = asyncio.get_running_loop()
        fut: asyncio.Future[Resp3Connection] = loop.create_future()
        self._waiters.append(fut)
        return await fut

    def release(self, conn: Resp3Connection) -> None:
        self._active -= 1
        if self._waiters:
            waiter = self._waiters.pop(0)
            self._active += 1
            waiter.set_result(conn)
        else:
            self._idle.append(conn)

    async def close(self) -> None:
        for conn in self._idle:
            conn.close()
            await conn.wait_closed()
        self._idle.clear()


def _infer_error_code(message: str) -> str:
    """Infer a structured error code from an engine error message.

    Engines send generic ``ERR {message}`` errors. This maps known message
    patterns back to the structured codes defined in protocol.toml.
    """
    m = message.lower()
    if "not found" in m:
        return "NOTFOUND"
    if "already exists" in m:
        return "EXISTS"
    if "is deleted" in m or "soft-revoked" in m:
        return "DELETED"
    if "access denied" in m or "policy denied" in m:
        return "DENIED"
    if "not authenticated" in m:
        return "NOT_AUTHENTICATED"
    if "verification failed" in m:
        return "VERIFICATION_FAILED"
    if "account locked" in m:
        return "ACCOUNT_LOCKED"
    if "invalid token" in m or "token reuse" in m:
        return "INVALID_TOKEN"
    if "invalid argument" in m or "invalid path" in m or "bad argument" in m:
        return "BADARG"
    if "unknown command" in m:
        return "BADARG"
    if "schema validation" in m:
        return "SCHEMA_VALIDATION"
    if "missing" in m and "field" in m:
        return "MISSING_FIELD"
    if "invalid field" in m:
        return "INVALID_FIELD"
    if "capability" in m or "unavailable" in m:
        return "CAPABILITY_MISSING"
    if "retired" in m:
        return "RETIRED"
    if "disabled" in m:
        return "DISABLED"
    if "shredded" in m or "crypto-shred" in m:
        return "SHREDDED"
    if "revoked" in m:
        return "REVOKED"
    if "encryption failed" in m or "decryption failed" in m:
        return "CRYPTO"
    return "ERR"


def _parse_response(raw: WireValue) -> dict[str, Any]:
    """Normalize a wire value into a dict response."""
    if raw is None:
        return {}
    if isinstance(raw, str):
        try:
            parsed = json.loads(raw)
            if isinstance(parsed, dict):
                return parsed
        except (json.JSONDecodeError, ValueError):
            pass
        return {"data": raw}
    if isinstance(raw, int):
        return {"value": raw}
    if isinstance(raw, dict):
        return raw
    return {"data": raw}


class Resp3Transport(Transport):
    """RESP3 transport for direct engine connections.

    Each engine gets its own connection pool. Commands are sent as RESP3
    arrays of bulk strings.
    """

    def __init__(self, uri: str) -> None:
        parsed = _parse_uri(uri)
        self._pool = ConnectionPool(
            host=parsed["host"],
            port=parsed["port"],
            tls=parsed["tls"],
            max_connections=10,
            token=parsed["token"],
        )

    async def execute(self, engine: str, args: list[str]) -> dict[str, Any]:
        conn = await self._pool.acquire()
        try:
            raw = await conn.execute(*args)
            return _parse_response(raw)
        finally:
            self._pool.release(conn)

    async def execute_many(
        self,
        engine: str,
        args_list: list[list[str]],
    ) -> list[dict[str, Any]]:
        if not args_list:
            return []
        conn = await self._pool.acquire()
        try:
            results: list[dict[str, Any]] = []
            for args in args_list:
                raw = await conn.execute(*args)
                results.append(_parse_response(raw))
            return results
        finally:
            self._pool.release(conn)

    async def execute_pipeline(
        self,
        engine: str,
        commands: list[list[str]],
        request_id: str | None = None,
    ) -> list[dict[str, Any]]:
        conn = await self._pool.acquire()
        try:
            raw = await conn.execute_pipeline_frame(["PIPELINE"], commands, request_id)
            if not isinstance(raw, list):
                from ..errors import ShrouDBError

                raise ShrouDBError("ERR", "PIPELINE response was not an array")
            return [_parse_response(item) for item in raw]
        finally:
            self._pool.release(conn)

    async def close(self) -> None:
        await self._pool.close()


class MoatResp3Transport(Transport):
    """RESP3 transport for Moat gateway connections.

    Commands are prefixed with the engine name before sending.
    """

    def __init__(self, uri: str) -> None:
        parsed = _parse_uri(uri)
        self._pool = ConnectionPool(
            host=parsed["host"],
            port=parsed["port"],
            tls=parsed["tls"],
            max_connections=10,
            token=parsed["token"],
        )

    async def execute(self, engine: str, args: list[str]) -> dict[str, Any]:
        prefixed = [engine.upper(), *args]
        conn = await self._pool.acquire()
        try:
            raw = await conn.execute(*prefixed)
            return _parse_response(raw)
        finally:
            self._pool.release(conn)

    async def execute_many(
        self,
        engine: str,
        args_list: list[list[str]],
    ) -> list[dict[str, Any]]:
        if not args_list:
            return []
        prefix = engine.upper()
        conn = await self._pool.acquire()
        try:
            results: list[dict[str, Any]] = []
            for args in args_list:
                raw = await conn.execute(prefix, *args)
                results.append(_parse_response(raw))
            return results
        finally:
            self._pool.release(conn)

    async def execute_pipeline(
        self,
        engine: str,
        commands: list[list[str]],
        request_id: str | None = None,
    ) -> list[dict[str, Any]]:
        conn = await self._pool.acquire()
        try:
            raw = await conn.execute_pipeline_frame(
                [engine.upper(), "PIPELINE"], commands, request_id
            )
            if not isinstance(raw, list):
                from ..errors import ShrouDBError

                raise ShrouDBError("ERR", "PIPELINE response was not an array")
            return [_parse_response(item) for item in raw]
        finally:
            self._pool.release(conn)

    async def close(self) -> None:
        await self._pool.close()
