# Auto-generated by shroudb-codegen. Do not edit.

from __future__ import annotations

from typing import Any

from ._transport._interface import Transport
from ._transport._http import HttpTransport
from ._transport._resp3 import Resp3Transport, MoatResp3Transport
from .engines.shroudb import ShroudbNamespace
from .engines.cipher import CipherNamespace
from .engines.sigil import SigilNamespace
from .engines.veil import VeilNamespace
from .engines.sentry import SentryNamespace
from .engines.forge import ForgeNamespace
from .engines.keep import KeepNamespace
from .engines.courier import CourierNamespace
from .engines.chronicle import ChronicleNamespace
from .engines.stash import StashNamespace


class _NoTransport(Transport):
    """Placeholder transport that raises on any call."""

    def __init__(self, engine: str) -> None:
        self._engine = engine

    async def execute(self, engine: str, args: list[str]) -> dict[str, Any]:
        raise RuntimeError(
            f"No transport configured for {self._engine}. "
            f"Provide a moat URL or {self._engine} URI."
        )

    async def execute_many(
        self,
        engine: str,
        args_list: list[list[str]],
    ) -> list[dict[str, Any]]:
        raise RuntimeError(
            f"No transport configured for {self._engine}. "
            f"Provide a moat URL or {self._engine} URI."
        )

    async def execute_pipeline(
        self,
        engine: str,
        commands: list[list[str]],
        request_id: str | None = None,
    ) -> list[dict[str, Any]]:
        raise RuntimeError(
            f"No transport configured for {self._engine}. "
            f"Provide a moat URL or {self._engine} URI."
        )

    async def close(self) -> None:
        pass


class ShrouDB:
    """ShrouDB unified client.

    Provides namespaced access to all ShrouDB engines. Each engine is
    accessible as a property (e.g., ``db.cipher.encrypt(...)``).

    Supply a ``moat`` URL to route all engines through a Moat gateway,
    or individual engine URIs for direct connections.
    """

    def __init__(
        self,
        *,
        moat: str | None = None,
        token: str | None = None,
        shroudb: str | None = None,
        cipher: str | None = None,
        sigil: str | None = None,
        veil: str | None = None,
        sentry: str | None = None,
        forge: str | None = None,
        keep: str | None = None,
        courier: str | None = None,
        chronicle: str | None = None,
        stash: str | None = None,
    ) -> None:
        self._transports: list[Transport] = []

        default_transport: Transport | None = None
        if moat is not None:
            if moat.startswith("http://") or moat.startswith("https://"):
                prefixes: dict[str, str] = {
                    "shroudb": "/v1/shroudb",
                    "cipher": "/v1/cipher",
                    "sigil": "/v1/sigil",
                    "veil": "/v1/veil",
                    "sentry": "/v1/sentry",
                    "forge": "/v1/forge",
                    "keep": "/v1/keep",
                    "courier": "/v1/courier",
                    "chronicle": "/v1/chronicle",
                    "stash": "/v1/stash",
                }
                default_transport = HttpTransport(moat, token, prefixes)
            else:
                default_transport = MoatResp3Transport(moat)
            self._transports.append(default_transport)

        if shroudb is not None:
            _t_shroudb = Resp3Transport(shroudb)
            self._transports.append(_t_shroudb)
            self.shroudb: ShroudbNamespace = ShroudbNamespace(_t_shroudb, "shroudb")
        elif default_transport is not None:
            self.shroudb = ShroudbNamespace(default_transport, "shroudb")
        else:
            self.shroudb = ShroudbNamespace(_NoTransport("shroudb"), "shroudb")

        if cipher is not None:
            _t_cipher = Resp3Transport(cipher)
            self._transports.append(_t_cipher)
            self.cipher: CipherNamespace = CipherNamespace(_t_cipher, "cipher")
        elif default_transport is not None:
            self.cipher = CipherNamespace(default_transport, "cipher")
        else:
            self.cipher = CipherNamespace(_NoTransport("cipher"), "cipher")

        if sigil is not None:
            _t_sigil = Resp3Transport(sigil)
            self._transports.append(_t_sigil)
            self.sigil: SigilNamespace = SigilNamespace(_t_sigil, "sigil")
        elif default_transport is not None:
            self.sigil = SigilNamespace(default_transport, "sigil")
        else:
            self.sigil = SigilNamespace(_NoTransport("sigil"), "sigil")

        if veil is not None:
            _t_veil = Resp3Transport(veil)
            self._transports.append(_t_veil)
            self.veil: VeilNamespace = VeilNamespace(_t_veil, "veil")
        elif default_transport is not None:
            self.veil = VeilNamespace(default_transport, "veil")
        else:
            self.veil = VeilNamespace(_NoTransport("veil"), "veil")

        if sentry is not None:
            _t_sentry = Resp3Transport(sentry)
            self._transports.append(_t_sentry)
            self.sentry: SentryNamespace = SentryNamespace(_t_sentry, "sentry")
        elif default_transport is not None:
            self.sentry = SentryNamespace(default_transport, "sentry")
        else:
            self.sentry = SentryNamespace(_NoTransport("sentry"), "sentry")

        if forge is not None:
            _t_forge = Resp3Transport(forge)
            self._transports.append(_t_forge)
            self.forge: ForgeNamespace = ForgeNamespace(_t_forge, "forge")
        elif default_transport is not None:
            self.forge = ForgeNamespace(default_transport, "forge")
        else:
            self.forge = ForgeNamespace(_NoTransport("forge"), "forge")

        if keep is not None:
            _t_keep = Resp3Transport(keep)
            self._transports.append(_t_keep)
            self.keep: KeepNamespace = KeepNamespace(_t_keep, "keep")
        elif default_transport is not None:
            self.keep = KeepNamespace(default_transport, "keep")
        else:
            self.keep = KeepNamespace(_NoTransport("keep"), "keep")

        if courier is not None:
            _t_courier = Resp3Transport(courier)
            self._transports.append(_t_courier)
            self.courier: CourierNamespace = CourierNamespace(_t_courier, "courier")
        elif default_transport is not None:
            self.courier = CourierNamespace(default_transport, "courier")
        else:
            self.courier = CourierNamespace(_NoTransport("courier"), "courier")

        if chronicle is not None:
            _t_chronicle = Resp3Transport(chronicle)
            self._transports.append(_t_chronicle)
            self.chronicle: ChronicleNamespace = ChronicleNamespace(_t_chronicle, "chronicle")
        elif default_transport is not None:
            self.chronicle = ChronicleNamespace(default_transport, "chronicle")
        else:
            self.chronicle = ChronicleNamespace(_NoTransport("chronicle"), "chronicle")

        if stash is not None:
            _t_stash = Resp3Transport(stash)
            self._transports.append(_t_stash)
            self.stash: StashNamespace = StashNamespace(_t_stash, "stash")
        elif default_transport is not None:
            self.stash = StashNamespace(default_transport, "stash")
        else:
            self.stash = StashNamespace(_NoTransport("stash"), "stash")

    async def close(self) -> None:
        """Close all connections and release resources."""
        for transport in self._transports:
            await transport.close()

    async def __aenter__(self) -> ShrouDB:
        return self

    async def __aexit__(self, *exc: object) -> None:
        await self.close()
