# Auto-generated by shroudb-codegen. Do not edit.

from __future__ import annotations


class ShrouDBError(Exception):
    """Base error class for all ShrouDB operations."""

    def __init__(self, code: str, message: str) -> None:
        super().__init__(f"{code} {message}")
        self.code = code
        self.message = message

    @classmethod
    def _from_server(cls, code: str, detail: str) -> ShrouDBError:
        """Create from a server error response."""
        return cls(code, detail)

    def __repr__(self) -> str:
        return f"ShrouDBError(code={self.code!r}, message={self.message!r})"


class ErrorCode:
    """Known ShrouDB error codes."""

    ACCOUNT_LOCKED: str = "ACCOUNT_LOCKED"
    """Account locked after too many failed attempts"""

    ADAPTER: str = "ADAPTER"
    """Delivery adapter failure"""

    AUTH_REQUIRED: str = "AUTH_REQUIRED"
    """Authentication required"""

    BADARG: str = "BADARG"
    """Missing or invalid argument"""

    BAD_ARG: str = "BAD_ARG"
    """Missing or malformed command argument"""

    CAPABILITY_MISSING: str = "CAPABILITY_MISSING"
    """Required engine capability not available (e.g., Cipher for PII fields)"""

    CIPHER_UNAVAILABLE: str = "CIPHER_UNAVAILABLE"
    """Cipher engine not available for envelope encryption"""

    CRYPTO: str = "CRYPTO"
    """Encryption or decryption failed"""

    DECRYPT: str = "DECRYPT"
    """Cipher decryption failed"""

    DELETED: str = "DELETED"
    """Secret has been soft-deleted"""

    DENIED: str = "DENIED"
    """Authentication required or insufficient permissions"""

    DISABLED: str = "DISABLED"
    """Keyring is disabled"""

    ENCRYPTION: str = "ENCRYPTION"
    """Encryption or decryption failed"""

    ENTITY_EXISTS: str = "ENTITY_EXISTS"
    """Entity already exists"""

    ENTITY_NOT_FOUND: str = "ENTITY_NOT_FOUND"
    """Entity does not exist"""

    EXISTS: str = "EXISTS"
    """Keyring already exists"""

    IMPORT_FAILED: str = "IMPORT_FAILED"
    """Password import failed (invalid hash format)"""

    INTERNAL: str = "INTERNAL"
    """Unexpected server error"""

    INVALID_ARGUMENT: str = "INVALID_ARGUMENT"
    """Invalid argument"""

    INVALID_FIELD: str = "INVALID_FIELD"
    """Field value is invalid or field cannot be updated via this path"""

    INVALID_TOKEN: str = "INVALID_TOKEN"
    """Token is invalid, expired, or revoked"""

    MISSING_FIELD: str = "MISSING_FIELD"
    """Required field missing from request"""

    NAMESPACE_EXISTS: str = "NAMESPACE_EXISTS"
    """Namespace already exists"""

    NAMESPACE_NOT_EMPTY: str = "NAMESPACE_NOT_EMPTY"
    """Namespace is not empty (use FORCE to override)"""

    NAMESPACE_NOT_FOUND: str = "NAMESPACE_NOT_FOUND"
    """Namespace does not exist"""

    NOKEY: str = "NOKEY"
    """No active signing key available"""

    NOTFOUND: str = "NOTFOUND"
    """Keyring or key version not found"""

    NOT_AUTHENTICATED: str = "NOT_AUTHENTICATED"
    """No auth token provided on this connection"""

    NOT_FOUND: str = "NOT_FOUND"
    """Key or resource does not exist"""

    NOT_READY: str = "NOT_READY"
    """Server is not in READY state"""

    OBJECT_STORE: str = "OBJECT_STORE"
    """S3 object store operation failed"""

    PIPELINE_ABORTED: str = "PIPELINE_ABORTED"
    """Pipeline command failed, all commands rolled back"""

    POLICY: str = "POLICY"
    """Operation denied by keyring policy"""

    RETIRED: str = "RETIRED"
    """Key version is retired — use REWRAP"""

    REVOKED: str = "REVOKED"
    """Blob has been soft-revoked"""

    SCHEMA_EXISTS: str = "SCHEMA_EXISTS"
    """Schema already exists"""

    SCHEMA_NOT_FOUND: str = "SCHEMA_NOT_FOUND"
    """Schema does not exist"""

    SCHEMA_VALIDATION: str = "SCHEMA_VALIDATION"
    """Schema definition is invalid"""

    SHREDDED: str = "SHREDDED"
    """Blob has been crypto-shredded (unrecoverable)"""

    SIGNING: str = "SIGNING"
    """Failed to sign decision"""

    STORAGE: str = "STORAGE"
    """Backend storage error"""

    TOKEN_REUSE: str = "TOKEN_REUSE"
    """Refresh token reuse detected — entire family revoked"""

    VALIDATION_FAILED: str = "VALIDATION_FAILED"
    """Metadata validation failed against namespace schema"""

    VERIFICATION_FAILED: str = "VERIFICATION_FAILED"
    """Credential verification failed (wrong password)"""

    VERSION_NOTFOUND: str = "VERSION_NOTFOUND"
    """Requested version does not exist"""

    VERSION_NOT_FOUND: str = "VERSION_NOT_FOUND"
    """Requested version does not exist"""

    WRONGTYPE: str = "WRONGTYPE"
    """Operation not supported for this keyring type"""

