# Auto-generated by shroudb-codegen. Do not edit.

from __future__ import annotations

from dataclasses import dataclass
from typing import Any


@dataclass(frozen=True)
class ChronicleActorsResponse:
    """Response from ``chronicle.ACTORS()``."""

    actors: list[Any]
    status: str

@dataclass(frozen=True)
class ChronicleAuthResponse:
    """Response from ``chronicle.AUTH()``."""

    status: str

@dataclass(frozen=True)
class ChronicleCommandListResponse:
    """Response from ``chronicle.COMMAND_LIST()``."""

    commands: list[Any]

@dataclass(frozen=True)
class ChronicleCountResponse:
    """Response from ``chronicle.COUNT()``."""

    count: int
    scanned: int
    status: str

@dataclass(frozen=True)
class ChronicleErrorsResponse:
    """Response from ``chronicle.ERRORS()``."""

    errors: list[Any]
    status: str

@dataclass(frozen=True)
class ChronicleHealthResponse:
    """Response from ``chronicle.HEALTH()``."""

    events: int
    status: str

@dataclass(frozen=True)
class ChronicleHotspotsResponse:
    """Response from ``chronicle.HOTSPOTS()``."""

    hotspots: list[Any]
    status: str

@dataclass(frozen=True)
class ChronicleIngestResponse:
    """Response from ``chronicle.INGEST()``."""

    status: str

@dataclass(frozen=True)
class ChronicleIngestBatchResponse:
    """Response from ``chronicle.INGEST_BATCH()``."""

    ingested: int
    status: str

@dataclass(frozen=True)
class ChronicleQueryResponse:
    """Response from ``chronicle.QUERY()``."""

    events: list[Any]
    matched: int
    scanned: int
    status: str

@dataclass(frozen=True)
class ChronicleVerifyResponse:
    """Response from ``chronicle.VERIFY()``."""

    per_tenant: dict[str, Any]
    status: str
    total: int
    verified: int
