# Auto-generated by shroudb-codegen. Do not edit.

from __future__ import annotations

from dataclasses import dataclass
from typing import Any


@dataclass(frozen=True)
class ChronicleActorsResponse:
    """Response from ``chronicle.ACTORS()``."""

    entries: list[Any]

@dataclass(frozen=True)
class ChronicleAuthResponse:
    """Response from ``chronicle.AUTH()``."""

    status: str

@dataclass(frozen=True)
class ChronicleCountResponse:
    """Response from ``chronicle.COUNT()``."""

    count: int

@dataclass(frozen=True)
class ChronicleErrorsResponse:
    """Response from ``chronicle.ERRORS()``."""

    entries: list[Any]

@dataclass(frozen=True)
class ChronicleHealthResponse:
    """Response from ``chronicle.HEALTH()``."""

    status: str

@dataclass(frozen=True)
class ChronicleHotspotsResponse:
    """Response from ``chronicle.HOTSPOTS()``."""

    entries: list[Any]

@dataclass(frozen=True)
class ChronicleIngestResponse:
    """Response from ``chronicle.INGEST()``."""

    status: str

@dataclass(frozen=True)
class ChronicleIngestBatchResponse:
    """Response from ``chronicle.INGEST_BATCH()``."""

    ingested: int
    status: str

@dataclass(frozen=True)
class ChronicleQueryResponse:
    """Response from ``chronicle.QUERY()``."""

    events: list[Any]
