# Auto-generated by shroudb-codegen. Do not edit.

from __future__ import annotations

from dataclasses import dataclass
from typing import Any


@dataclass(frozen=True)
class CipherAuthResponse:
    """Response from ``cipher.auth()``."""

    # OK on success
    status: str

@dataclass(frozen=True)
class CipherCommandListResponse:
    """Response from ``cipher.command_list()``."""

    # Number of supported commands
    count: int
    # List of command verb strings
    commands: list[Any]

@dataclass(frozen=True)
class CipherDecryptResponse:
    """Response from ``cipher.decrypt()``."""

    # Decrypted data
    plaintext: str

@dataclass(frozen=True)
class CipherEncryptResponse:
    """Response from ``cipher.encrypt()``."""

    # Encrypted data with embedded key version
    ciphertext: str
    # Key version used for encryption
    key_version: int

@dataclass(frozen=True)
class CipherGenerateDataKeyResponse:
    """Response from ``cipher.generate_data_key()``."""

    # Plaintext DEK (use for local encryption, then discard)
    plaintext_key: str
    # Wrapped DEK (store alongside ciphertext, unwrap via DECRYPT)
    wrapped_key: str
    # Key version used to wrap
    key_version: int

@dataclass(frozen=True)
class CipherHealthResponse:
    """Response from ``cipher.health()``."""

    # ok
    status: str

@dataclass(frozen=True)
class CipherKeyInfoResponse:
    """Response from ``cipher.key_info()``."""

    # Keyring name
    keyring: str
    # Keyring algorithm
    algorithm: str
    # Currently active key version
    active_version: int
    # List of all key versions with state
    versions: list[Any]

@dataclass(frozen=True)
class CipherKeyringCreateResponse:
    """Response from ``cipher.keyring_create()``."""

    # Keyring name
    keyring: str
    # Algorithm
    algorithm: str
    # Active key version
    active_version: int

@dataclass(frozen=True)
class CipherKeyringListResponse:
    """Response from ``cipher.keyring_list()``."""

    # List of keyring names
    keyrings: list[Any]

@dataclass(frozen=True)
class CipherPingResponse:
    """Response from ``cipher.ping()``."""

    # Always PONG
    message: str

@dataclass(frozen=True)
class CipherRewrapResponse:
    """Response from ``cipher.rewrap()``."""

    # Re-encrypted ciphertext with new key version
    ciphertext: str
    # New key version used
    key_version: int

@dataclass(frozen=True)
class CipherRotateResponse:
    """Response from ``cipher.rotate()``."""

    # Whether rotation occurred
    rotated: bool
    # Active key version after operation
    key_version: int
    # Previous active key version
    previous_version: int | None

@dataclass(frozen=True)
class CipherSignResponse:
    """Response from ``cipher.sign()``."""

    # Hex-encoded detached signature
    signature: str
    # Key version used
    key_version: int

@dataclass(frozen=True)
class CipherVerifySignatureResponse:
    """Response from ``cipher.verify_signature()``."""

    # Whether the signature is valid
    valid: bool
