# Auto-generated by shroudb-codegen. Do not edit.

from __future__ import annotations

from dataclasses import dataclass
from typing import Any


@dataclass(frozen=True)
class CourierAuthResponse:
    """Response from ``courier.AUTH()``."""

    status: str

@dataclass(frozen=True)
class CourierChannelCreateResponse:
    """Response from ``courier.CHANNEL_CREATE()``."""

    channel_type: str
    name: str
    status: str

@dataclass(frozen=True)
class CourierChannelDeleteResponse:
    """Response from ``courier.CHANNEL_DELETE()``."""

    name: str
    status: str

@dataclass(frozen=True)
class CourierChannelGetResponse:
    """Response from ``courier.CHANNEL_GET()``."""

    channel_type: str
    created_at: int
    enabled: bool
    name: str

@dataclass(frozen=True)
class CourierChannelListResponse:
    """Response from ``courier.CHANNEL_LIST()``."""

    channels: list[Any]
    count: int
    status: str

@dataclass(frozen=True)
class CourierCommandListResponse:
    """Response from ``courier.COMMAND_LIST()``."""

    commands: list[Any]
    count: int

@dataclass(frozen=True)
class CourierDeliverResponse:
    """Response from ``courier.DELIVER()``."""

    channel: str
    delivered_at: int
    delivery_id: str
    status: str

@dataclass(frozen=True)
class CourierHealthResponse:
    """Response from ``courier.HEALTH()``."""

    channels: int
    status: str

@dataclass(frozen=True)
class CourierNotifyEventResponse:
    """Response from ``courier.NOTIFY_EVENT()``."""

    channel: str
    delivered_at: int
    delivery_id: str
    status: str
