# Auto-generated by shroudb-codegen. Do not edit.

from __future__ import annotations

from dataclasses import dataclass
from typing import Any


@dataclass(frozen=True)
class ForgeCaCreateResponse:
    """Response from ``forge.CA_CREATE()``."""

    active_version: int
    algorithm: str
    name: str
    subject: str

@dataclass(frozen=True)
class ForgeCaExportResponse:
    """Response from ``forge.CA_EXPORT()``."""

    certificate_pem: str

@dataclass(frozen=True)
class ForgeCaInfoResponse:
    """Response from ``forge.CA_INFO()``."""

    algorithm: str
    key_versions: list[Any]
    name: str
    subject: str

@dataclass(frozen=True)
class ForgeCaListResponse:
    """Response from ``forge.CA_LIST()``."""

    cas: list[Any]

@dataclass(frozen=True)
class ForgeCaRotateResponse:
    """Response from ``forge.CA_ROTATE()``."""

    key_version: int
    previous_version: int
    rotated: bool

@dataclass(frozen=True)
class ForgeInspectResponse:
    """Response from ``forge.INSPECT()``."""

    certificate_pem: str
    serial: str
    state: str
    subject: str

@dataclass(frozen=True)
class ForgeIssueResponse:
    """Response from ``forge.ISSUE()``."""

    certificate_pem: str
    private_key_pem: str
    serial: str

@dataclass(frozen=True)
class ForgeIssueFromCsrResponse:
    """Response from ``forge.ISSUE_FROM_CSR()``."""

    certificate_pem: str
    serial: str

@dataclass(frozen=True)
class ForgeListCertsResponse:
    """Response from ``forge.LIST_CERTS()``."""

    certs: list[Any]
    count: int

@dataclass(frozen=True)
class ForgeRenewResponse:
    """Response from ``forge.RENEW()``."""

    certificate_pem: str
    private_key_pem: str
    serial: str

@dataclass(frozen=True)
class ForgeRevokeResponse:
    """Response from ``forge.REVOKE()``."""

    status: str
