# Auto-generated by shroudb-codegen. Do not edit.

from __future__ import annotations

from dataclasses import dataclass
from typing import Any


@dataclass(frozen=True)
class KeepAuthResponse:
    """Response from ``keep.auth()``."""

    status: str

@dataclass(frozen=True)
class KeepCommandListResponse:
    """Response from ``keep.command_list()``."""

    count: int
    commands: list[Any]

@dataclass(frozen=True)
class KeepDeleteResponse:
    """Response from ``keep.delete()``."""

    status: str
    path: str
    deleted_at: int

@dataclass(frozen=True)
class KeepGetResponse:
    """Response from ``keep.get()``."""

    status: str
    path: str
    version: str
    value: str
    created_at: int
    created_by: str

@dataclass(frozen=True)
class KeepHealthResponse:
    """Response from ``keep.health()``."""

    status: str

@dataclass(frozen=True)
class KeepListResponse:
    """Response from ``keep.list()``."""

    status: str
    count: int
    paths: list[Any]

@dataclass(frozen=True)
class KeepPurgeResponse:
    """Response from ``keep.purge()``."""

    status: str
    path: str
    purged_at: str

@dataclass(frozen=True)
class KeepPutResponse:
    """Response from ``keep.put()``."""

    status: str
    path: str
    version: str

@dataclass(frozen=True)
class KeepRekeyResponse:
    """Response from ``keep.rekey()``."""

    status: str
    rekeyed_secrets: int
    rekeyed_versions: int

@dataclass(frozen=True)
class KeepRotateResponse:
    """Response from ``keep.rotate()``."""

    status: str
    path: str
    version: str

@dataclass(frozen=True)
class KeepVersionsResponse:
    """Response from ``keep.versions()``."""

    status: str
    path: str
    version_count: int
    versions: list[Any]
    deleted: bool
