# Auto-generated by shroudb-codegen. Do not edit.

from __future__ import annotations

from dataclasses import dataclass
from typing import Any


@dataclass(frozen=True)
class ScrollAckResponse:
    """Response from ``scroll.ACK()``."""

    status: str

@dataclass(frozen=True)
class ScrollAppendResponse:
    """Response from ``scroll.APPEND()``."""

    offset: int
    status: str

@dataclass(frozen=True)
class ScrollAuthResponse:
    """Response from ``scroll.AUTH()``."""

    status: str

@dataclass(frozen=True)
class ScrollClaimResponse:
    """Response from ``scroll.CLAIM()``."""

    claimed: list[Any]
    status: str

@dataclass(frozen=True)
class ScrollCommandListResponse:
    """Response from ``scroll.COMMAND LIST()``."""

    commands: list[Any]

@dataclass(frozen=True)
class ScrollCreateGroupResponse:
    """Response from ``scroll.CREATE_GROUP()``."""

    status: str

@dataclass(frozen=True)
class ScrollDeleteGroupResponse:
    """Response from ``scroll.DELETE_GROUP()``."""

    status: str

@dataclass(frozen=True)
class ScrollDeleteLogResponse:
    """Response from ``scroll.DELETE_LOG()``."""

    status: str

@dataclass(frozen=True)
class ScrollGroupInfoResponse:
    """Response from ``scroll.GROUP_INFO()``."""

    created_at_ms: int
    group: str
    last_delivered_offset: int
    log: str
    members: list[Any]
    pending_count: int

@dataclass(frozen=True)
class ScrollHealthResponse:
    """Response from ``scroll.HEALTH()``."""

    status: str

@dataclass(frozen=True)
class ScrollHelloResponse:
    """Response from ``scroll.HELLO()``."""

    capabilities: list[Any]
    commands: list[Any]
    engine: str
    protocol: str
    version: str

@dataclass(frozen=True)
class ScrollLogInfoResponse:
    """Response from ``scroll.LOG_INFO()``."""

    created_at_ms: int
    entries_minted: int
    groups: list[Any]
    latest_offset: str
    log: str

@dataclass(frozen=True)
class ScrollReadResponse:
    """Response from ``scroll.READ()``."""

    entries: list[Any]
    status: str

@dataclass(frozen=True)
class ScrollReadGroupResponse:
    """Response from ``scroll.READ_GROUP()``."""

    entries: list[Any]
    status: str

@dataclass(frozen=True)
class ScrollReplayResponse:
    """Response from ``scroll.REPLAY()``."""

    status: str

@dataclass(frozen=True)
class ScrollTailResponse:
    """Response from ``scroll.TAIL()``."""

    entries: list[Any]
    status: str

@dataclass(frozen=True)
class ScrollTrimResponse:
    """Response from ``scroll.TRIM()``."""

    deleted: int
    status: str
