# Auto-generated by shroudb-codegen. Do not edit.

from __future__ import annotations

from dataclasses import dataclass
from typing import Any


@dataclass(frozen=True)
class SentryAuthResponse:
    """Response from ``sentry.AUTH()``."""

    status: str

@dataclass(frozen=True)
class SentryCommandListResponse:
    """Response from ``sentry.COMMAND_LIST()``."""

    commands: list[Any]
    status: str

@dataclass(frozen=True)
class SentryEvaluateResponse:
    """Response from ``sentry.EVALUATE()``."""

    cache_until: int
    decision: str
    matched_policy: str
    status: str
    token: str

@dataclass(frozen=True)
class SentryHealthResponse:
    """Response from ``sentry.HEALTH()``."""

    policy_count: int
    status: str

@dataclass(frozen=True)
class SentryJwksResponse:
    """Response from ``sentry.JWKS()``."""

    keys: list[Any]

@dataclass(frozen=True)
class SentryKeyInfoResponse:
    """Response from ``sentry.KEY_INFO()``."""

    active_kid: str
    active_version: int
    algorithm: str
    decision_ttl_secs: int
    drain_days: int
    jwks_keys: int
    rotation_days: int
    status: str
    total_versions: int

@dataclass(frozen=True)
class SentryKeyRotateResponse:
    """Response from ``sentry.KEY_ROTATE()``."""

    key_version: int
    previous_version: int
    rotated: bool
    status: str

@dataclass(frozen=True)
class SentryPolicyCreateResponse:
    """Response from ``sentry.POLICY_CREATE()``."""

    effect: str
    name: str
    priority: int
    status: str
    version: int

@dataclass(frozen=True)
class SentryPolicyDeleteResponse:
    """Response from ``sentry.POLICY_DELETE()``."""

    status: str

@dataclass(frozen=True)
class SentryPolicyGetResponse:
    """Response from ``sentry.POLICY_GET()``."""

    action: str
    conditions: str
    created_at: int
    description: str
    effect: str
    name: str
    principal: str
    priority: int
    resource: str
    status: str
    updated_at: int
    version: int

@dataclass(frozen=True)
class SentryPolicyHistoryResponse:
    """Response from ``sentry.POLICY_HISTORY()``."""

    count: int
    name: str
    status: str
    versions: list[Any]

@dataclass(frozen=True)
class SentryPolicyListResponse:
    """Response from ``sentry.POLICY_LIST()``."""

    count: int
    policies: list[Any]
    status: str

@dataclass(frozen=True)
class SentryPolicyUpdateResponse:
    """Response from ``sentry.POLICY_UPDATE()``."""

    effect: str
    name: str
    priority: int
    status: str
    updated_at: int
    version: int
