# Auto-generated by shroudb-codegen. Do not edit.

from __future__ import annotations

from dataclasses import dataclass
from typing import Any


@dataclass(frozen=True)
class ShroudbAuthResponse:
    """Response from ``shroudb.AUTH()``."""

    actor: str

@dataclass(frozen=True)
class ShroudbCommandListResponse:
    """Response from ``shroudb.COMMAND LIST()``."""

    commands: list[Any]
    count: int

@dataclass(frozen=True)
class ShroudbConfigGetResponse:
    """Response from ``shroudb.CONFIG GET()``."""

    key: str
    source: str
    value: str

@dataclass(frozen=True)
class ShroudbDeleteResponse:
    """Response from ``shroudb.DELETE()``."""

    version: int

@dataclass(frozen=True)
class ShroudbDelifResponse:
    """Response from ``shroudb.DELIF()``."""

    version: int

@dataclass(frozen=True)
class ShroudbDelprefixResponse:
    """Response from ``shroudb.DELPREFIX()``."""

    deleted: int

@dataclass(frozen=True)
class ShroudbGetResponse:
    """Response from ``shroudb.GET()``."""

    key: str
    metadata: str
    value: str
    version: int

@dataclass(frozen=True)
class ShroudbHealthResponse:
    """Response from ``shroudb.HEALTH()``."""

    message: str

@dataclass(frozen=True)
class ShroudbListResponse:
    """Response from ``shroudb.LIST()``."""

    cursor: str
    keys: list[Any]

@dataclass(frozen=True)
class ShroudbNamespaceInfoResponse:
    """Response from ``shroudb.NAMESPACE INFO()``."""

    created_at: int
    key_count: int
    name: str

@dataclass(frozen=True)
class ShroudbNamespaceListResponse:
    """Response from ``shroudb.NAMESPACE LIST()``."""

    cursor: str
    namespaces: list[Any]

@dataclass(frozen=True)
class ShroudbNamespaceValidateResponse:
    """Response from ``shroudb.NAMESPACE VALIDATE()``."""

    count: int
    reports: list[Any]

@dataclass(frozen=True)
class ShroudbPingResponse:
    """Response from ``shroudb.PING()``."""

    message: str

@dataclass(frozen=True)
class ShroudbPutResponse:
    """Response from ``shroudb.PUT()``."""

    version: int

@dataclass(frozen=True)
class ShroudbPutifResponse:
    """Response from ``shroudb.PUTIF()``."""

    version: int

@dataclass(frozen=True)
class ShroudbRekeyResponse:
    """Response from ``shroudb.REKEY()``."""

    message: str

@dataclass(frozen=True)
class ShroudbRekeyStatusResponse:
    """Response from ``shroudb.REKEY STATUS()``."""

    in_progress: bool
    progress: str
    segments_completed: int
    started_at: int
    total_segments: int

@dataclass(frozen=True)
class ShroudbVersionsResponse:
    """Response from ``shroudb.VERSIONS()``."""

    versions: list[Any]
