# Auto-generated by shroudb-codegen. Do not edit.

from __future__ import annotations

from dataclasses import dataclass
from typing import Any


@dataclass(frozen=True)
class SigilAuthResponse:
    """Response from ``sigil.AUTH()``."""

    status: str

@dataclass(frozen=True)
class SigilCredentialChangeResponse:
    """Response from ``sigil.CREDENTIAL_CHANGE()``."""

    status: str

@dataclass(frozen=True)
class SigilCredentialImportResponse:
    """Response from ``sigil.CREDENTIAL_IMPORT()``."""

    algorithm: str
    status: str

@dataclass(frozen=True)
class SigilCredentialResetResponse:
    """Response from ``sigil.CREDENTIAL_RESET()``."""

    status: str

@dataclass(frozen=True)
class SigilEnvelopeCreateResponse:
    """Response from ``sigil.ENVELOPE_CREATE()``."""

    created_at: int
    entity_id: str
    fields: dict[str, Any]
    status: str

@dataclass(frozen=True)
class SigilEnvelopeDeleteResponse:
    """Response from ``sigil.ENVELOPE_DELETE()``."""

    status: str

@dataclass(frozen=True)
class SigilEnvelopeGetResponse:
    """Response from ``sigil.ENVELOPE_GET()``."""

    created_at: int
    entity_id: str
    fields: dict[str, Any]
    updated_at: int

@dataclass(frozen=True)
class SigilEnvelopeImportResponse:
    """Response from ``sigil.ENVELOPE_IMPORT()``."""

    created_at: int
    entity_id: str
    fields: dict[str, Any]
    status: str

@dataclass(frozen=True)
class SigilEnvelopeLookupResponse:
    """Response from ``sigil.ENVELOPE_LOOKUP()``."""

    entity_id: str
    status: str

@dataclass(frozen=True)
class SigilEnvelopeUpdateResponse:
    """Response from ``sigil.ENVELOPE_UPDATE()``."""

    entity_id: str
    fields: dict[str, Any]
    status: str
    updated_at: int

@dataclass(frozen=True)
class SigilEnvelopeVerifyResponse:
    """Response from ``sigil.ENVELOPE_VERIFY()``."""

    status: str
    valid: bool

@dataclass(frozen=True)
class SigilHealthResponse:
    """Response from ``sigil.HEALTH()``."""

    status: str

@dataclass(frozen=True)
class SigilHelloResponse:
    """Response from ``sigil.HELLO()``."""

    capabilities: list[Any]
    commands: list[Any]
    engine: str
    protocol: str
    version: str

@dataclass(frozen=True)
class SigilPasswordChangeResponse:
    """Response from ``sigil.PASSWORD_CHANGE()``."""

    status: str

@dataclass(frozen=True)
class SigilPasswordImportResponse:
    """Response from ``sigil.PASSWORD_IMPORT()``."""

    algorithm: str
    status: str

@dataclass(frozen=True)
class SigilPasswordResetResponse:
    """Response from ``sigil.PASSWORD_RESET()``."""

    status: str

@dataclass(frozen=True)
class SigilPingResponse:
    """Response from ``sigil.PING()``."""

    status: str

@dataclass(frozen=True)
class SigilSchemaAlterResponse:
    """Response from ``sigil.SCHEMA_ALTER()``."""

    fields: int
    name: str
    status: str
    version: int

@dataclass(frozen=True)
class SigilSchemaRegisterResponse:
    """Response from ``sigil.SCHEMA_REGISTER()``."""

    status: str
    version: int

@dataclass(frozen=True)
class SigilSessionCreateResponse:
    """Response from ``sigil.SESSION_CREATE()``."""

    access_token: str
    expires_in: int
    refresh_token: str
    status: str

@dataclass(frozen=True)
class SigilSessionLoginResponse:
    """Response from ``sigil.SESSION_LOGIN()``."""

    access_token: str
    expires_in: int
    refresh_token: str
    status: str

@dataclass(frozen=True)
class SigilSessionRefreshResponse:
    """Response from ``sigil.SESSION_REFRESH()``."""

    access_token: str
    expires_in: int
    refresh_token: str
    status: str

@dataclass(frozen=True)
class SigilSessionRevokeResponse:
    """Response from ``sigil.SESSION_REVOKE()``."""

    status: str

@dataclass(frozen=True)
class SigilSessionRevokeAllResponse:
    """Response from ``sigil.SESSION_REVOKE_ALL()``."""

    revoked: int
    status: str

@dataclass(frozen=True)
class SigilUserCreateResponse:
    """Response from ``sigil.USER_CREATE()``."""

    created_at: int
    entity_id: str
    fields: dict[str, Any]
    status: str

@dataclass(frozen=True)
class SigilUserDeleteResponse:
    """Response from ``sigil.USER_DELETE()``."""

    status: str

@dataclass(frozen=True)
class SigilUserGetResponse:
    """Response from ``sigil.USER_GET()``."""

    created_at: int
    entity_id: str
    fields: dict[str, Any]
    updated_at: int

@dataclass(frozen=True)
class SigilUserImportResponse:
    """Response from ``sigil.USER_IMPORT()``."""

    created_at: int
    entity_id: str
    fields: dict[str, Any]
    status: str

@dataclass(frozen=True)
class SigilUserLookupResponse:
    """Response from ``sigil.USER_LOOKUP()``."""

    entity_id: str
    status: str

@dataclass(frozen=True)
class SigilUserUpdateResponse:
    """Response from ``sigil.USER_UPDATE()``."""

    entity_id: str
    fields: dict[str, Any]
    status: str
    updated_at: int

@dataclass(frozen=True)
class SigilUserVerifyResponse:
    """Response from ``sigil.USER_VERIFY()``."""

    status: str
    valid: bool
