# Auto-generated by shroudb-codegen. Do not edit.

from __future__ import annotations

from dataclasses import dataclass
from typing import Any


@dataclass(frozen=True)
class SigilCredentialChangeResponse:
    """Response from ``sigil.CREDENTIAL_CHANGE()``."""

    status: str

@dataclass(frozen=True)
class SigilCredentialImportResponse:
    """Response from ``sigil.CREDENTIAL_IMPORT()``."""

    algorithm: str

@dataclass(frozen=True)
class SigilCredentialResetResponse:
    """Response from ``sigil.CREDENTIAL_RESET()``."""

    status: str

@dataclass(frozen=True)
class SigilEnvelopeCreateResponse:
    """Response from ``sigil.ENVELOPE_CREATE()``."""

    created_at: int
    fields: dict[str, Any]
    id: str

@dataclass(frozen=True)
class SigilEnvelopeDeleteResponse:
    """Response from ``sigil.ENVELOPE_DELETE()``."""

    status: str

@dataclass(frozen=True)
class SigilEnvelopeGetResponse:
    """Response from ``sigil.ENVELOPE_GET()``."""

    created_at: int
    fields: dict[str, Any]
    id: str
    updated_at: int

@dataclass(frozen=True)
class SigilEnvelopeImportResponse:
    """Response from ``sigil.ENVELOPE_IMPORT()``."""

    created_at: int
    fields: dict[str, Any]
    id: str

@dataclass(frozen=True)
class SigilEnvelopeLookupResponse:
    """Response from ``sigil.ENVELOPE_LOOKUP()``."""

    created_at: int
    fields: dict[str, Any]
    id: str
    updated_at: int

@dataclass(frozen=True)
class SigilEnvelopeUpdateResponse:
    """Response from ``sigil.ENVELOPE_UPDATE()``."""

    fields: dict[str, Any]
    id: str
    updated_at: int

@dataclass(frozen=True)
class SigilEnvelopeVerifyResponse:
    """Response from ``sigil.ENVELOPE_VERIFY()``."""

    valid: bool

@dataclass(frozen=True)
class SigilHealthResponse:
    """Response from ``sigil.HEALTH()``."""

    status: str

@dataclass(frozen=True)
class SigilJwksResponse:
    """Response from ``sigil.JWKS()``."""

    keys: list[Any]

@dataclass(frozen=True)
class SigilPasswordChangeResponse:
    """Response from ``sigil.PASSWORD_CHANGE()``."""

    status: str

@dataclass(frozen=True)
class SigilPasswordImportResponse:
    """Response from ``sigil.PASSWORD_IMPORT()``."""

    algorithm: str

@dataclass(frozen=True)
class SigilPasswordResetResponse:
    """Response from ``sigil.PASSWORD_RESET()``."""

    status: str

@dataclass(frozen=True)
class SigilSchemaGetResponse:
    """Response from ``sigil.SCHEMA_GET()``."""

    schema: str

@dataclass(frozen=True)
class SigilSchemaListResponse:
    """Response from ``sigil.SCHEMA_LIST()``."""

    names: list[Any]

@dataclass(frozen=True)
class SigilSchemaRegisterResponse:
    """Response from ``sigil.SCHEMA_REGISTER()``."""

    version: int

@dataclass(frozen=True)
class SigilSessionCreateResponse:
    """Response from ``sigil.SESSION_CREATE()``."""

    access_token: str
    expires_in: int
    refresh_token: str

@dataclass(frozen=True)
class SigilSessionListResponse:
    """Response from ``sigil.SESSION_LIST()``."""

    sessions: list[Any]

@dataclass(frozen=True)
class SigilSessionRefreshResponse:
    """Response from ``sigil.SESSION_REFRESH()``."""

    access_token: str
    expires_in: int
    refresh_token: str

@dataclass(frozen=True)
class SigilSessionRevokeResponse:
    """Response from ``sigil.SESSION_REVOKE()``."""

    status: str

@dataclass(frozen=True)
class SigilSessionRevokeAllResponse:
    """Response from ``sigil.SESSION_REVOKE_ALL()``."""

    revoked: int

@dataclass(frozen=True)
class SigilUserCreateResponse:
    """Response from ``sigil.USER_CREATE()``."""

    created_at: int
    fields: dict[str, Any]
    user_id: str

@dataclass(frozen=True)
class SigilUserDeleteResponse:
    """Response from ``sigil.USER_DELETE()``."""

    status: str

@dataclass(frozen=True)
class SigilUserGetResponse:
    """Response from ``sigil.USER_GET()``."""

    created_at: int
    fields: dict[str, Any]
    updated_at: int
    user_id: str

@dataclass(frozen=True)
class SigilUserImportResponse:
    """Response from ``sigil.USER_IMPORT()``."""

    created_at: int
    fields: dict[str, Any]
    user_id: str

@dataclass(frozen=True)
class SigilUserUpdateResponse:
    """Response from ``sigil.USER_UPDATE()``."""

    fields: dict[str, Any]
    updated_at: int
    user_id: str

@dataclass(frozen=True)
class SigilUserVerifyResponse:
    """Response from ``sigil.USER_VERIFY()``."""

    valid: bool
