# Auto-generated by shroudb-codegen. Do not edit.

from __future__ import annotations

from dataclasses import dataclass
from typing import Any


@dataclass(frozen=True)
class StashFingerprintResponse:
    """Response from ``stash.fingerprint()``."""

    created_at: int
    s3_key: str
    status: str
    viewer_id: str

@dataclass(frozen=True)
class StashInspectResponse:
    """Response from ``stash.inspect()``."""

    blob_status: str
    client_encrypted: bool
    content_type: str
    created_at: int
    encrypted_size: int
    id: str
    key_version: int
    keyring: str
    plaintext_size: int
    status: str
    updated_at: int
    viewer_count: int

@dataclass(frozen=True)
class StashListResponse:
    """Response from ``stash.list()``."""

    blobs: list[Any]
    count: int
    status: str
    tenant: str

@dataclass(frozen=True)
class StashRevokeResponse:
    """Response from ``stash.revoke()``."""

    id: str
    revoke_mode: str
    status: str

@dataclass(frozen=True)
class StashRewrapResponse:
    """Response from ``stash.rewrap()``."""

    id: str
    key_version: int
    status: str
    updated_at: int

@dataclass(frozen=True)
class StashStoreResponse:
    """Response from ``stash.store()``."""

    client_encrypted: bool
    encrypted_size: int
    id: str
    key_version: int
    keyring: str
    plaintext_size: int
    s3_key: str
    status: str

@dataclass(frozen=True)
class StashTraceResponse:
    """Response from ``stash.trace()``."""

    blob_status: str
    id: str
    status: str
    viewer_count: int
    viewers: list[Any]
