# Auto-generated by shroudb-codegen. Do not edit.

from __future__ import annotations

from dataclasses import dataclass
from typing import Any


@dataclass(frozen=True)
class VeilAuthResponse:
    """Response from ``veil.AUTH()``."""

    status: str

@dataclass(frozen=True)
class VeilCommandListResponse:
    """Response from ``veil.COMMAND_LIST()``."""

    count: str
    commands: str

@dataclass(frozen=True)
class VeilDeleteResponse:
    """Response from ``veil.DELETE()``."""

    status: str
    id: str

@dataclass(frozen=True)
class VeilHealthResponse:
    """Response from ``veil.HEALTH()``."""

    status: str

@dataclass(frozen=True)
class VeilIndexCreateResponse:
    """Response from ``veil.INDEX_CREATE()``."""

    status: str
    index: str
    created_at: str

@dataclass(frozen=True)
class VeilIndexInfoResponse:
    """Response from ``veil.INDEX_INFO()``."""

    index: str
    created_at: str
    entry_count: str

@dataclass(frozen=True)
class VeilIndexListResponse:
    """Response from ``veil.INDEX_LIST()``."""

    items: str
    type: list[Any]

@dataclass(frozen=True)
class VeilPingResponse:
    """Response from ``veil.PING()``."""

    type: str
    value: str

@dataclass(frozen=True)
class VeilPutResponse:
    """Response from ``veil.PUT()``."""

    status: str
    id: str
    version: str

@dataclass(frozen=True)
class VeilSearchResponse:
    """Response from ``veil.SEARCH()``."""

    status: str
    scanned: str
    matched: str
    results: str

@dataclass(frozen=True)
class VeilTokenizeResponse:
    """Response from ``veil.TOKENIZE()``."""

    status: str
    words: str
    trigrams: str
    tokens: str
