# Auto-generated by shroudb-codegen. Do not edit.

from __future__ import annotations

import base64
import json
from typing import Any

from .._transport._interface import Transport
from ..types import chronicle as _types


class ChronicleNamespace:
    """Chronicle — Structured audit event engine"""

    def __init__(self, transport: Transport, engine: str = "chronicle") -> None:
        self._transport = transport
        self._engine = engine

    async def actors(self, filter_args: str | None = None) -> _types.ChronicleActorsResponse:
        """ACTORS — Active actors in time window"""
        args: list[str] = ["ACTORS"]
        if filter_args is not None:
            args.append("FILTER_ARGS")
            args.append(str(filter_args))
        result = await self._transport.execute(self._engine, args)
        return _types.ChronicleActorsResponse(entries=result.get("entries", None))

    async def auth(self, token: str) -> _types.ChronicleAuthResponse:
        """AUTH — Authenticate this connection"""
        args: list[str] = ["AUTH"]
        args.append(str(token))
        result = await self._transport.execute(self._engine, args)
        return _types.ChronicleAuthResponse(status=result.get("status", ""))

    async def count(self, filter_args: str | None = None) -> _types.ChronicleCountResponse:
        """COUNT — Count events matching filter predicates"""
        args: list[str] = ["COUNT"]
        if filter_args is not None:
            args.append("FILTER_ARGS")
            args.append(str(filter_args))
        result = await self._transport.execute(self._engine, args)
        return _types.ChronicleCountResponse(count=result.get("count", 0))

    async def errors(self, filter_args: str | None = None) -> _types.ChronicleErrorsResponse:
        """ERRORS — Error rates by action"""
        args: list[str] = ["ERRORS"]
        if filter_args is not None:
            args.append("FILTER_ARGS")
            args.append(str(filter_args))
        result = await self._transport.execute(self._engine, args)
        return _types.ChronicleErrorsResponse(entries=result.get("entries", None))

    async def health(self) -> _types.ChronicleHealthResponse:
        """HEALTH — Health check"""
        args: list[str] = ["HEALTH"]
        result = await self._transport.execute(self._engine, args)
        return _types.ChronicleHealthResponse(status=result.get("status", ""))

    async def hotspots(self, filter_args: str | None = None) -> _types.ChronicleHotspotsResponse:
        """HOTSPOTS — Top actors by event volume"""
        args: list[str] = ["HOTSPOTS"]
        if filter_args is not None:
            args.append("FILTER_ARGS")
            args.append(str(filter_args))
        result = await self._transport.execute(self._engine, args)
        return _types.ChronicleHotspotsResponse(entries=result.get("entries", None))

    async def ingest(self, event_json: dict[str, Any]) -> _types.ChronicleIngestResponse:
        """INGEST — Ingest a single structured audit event"""
        args: list[str] = ["INGEST"]
        args.append(event_json if isinstance(event_json, str) else json.dumps(event_json))
        result = await self._transport.execute(self._engine, args)
        return _types.ChronicleIngestResponse(status=result.get("status", ""))

    async def ingest_batch(self, events_json: dict[str, Any]) -> _types.ChronicleIngestBatchResponse:
        """INGEST_BATCH — Ingest multiple events in a single call"""
        args: list[str] = ["INGEST_BATCH"]
        args.append(events_json if isinstance(events_json, str) else json.dumps(events_json))
        result = await self._transport.execute(self._engine, args)
        return _types.ChronicleIngestBatchResponse(ingested=result.get("ingested", 0), status=result.get("status", ""))

    async def ping(self) -> dict[str, Any]:
        """PING — Keepalive"""
        args: list[str] = ["PING"]
        result = await self._transport.execute(self._engine, args)
        return result

    async def query(self, filter_args: str | None = None) -> _types.ChronicleQueryResponse:
        """QUERY — Query events with filter predicates"""
        args: list[str] = ["QUERY"]
        if filter_args is not None:
            args.append("FILTER_ARGS")
            args.append(str(filter_args))
        result = await self._transport.execute(self._engine, args)
        return _types.ChronicleQueryResponse(events=result.get("events", None))
