# Auto-generated by shroudb-codegen. Do not edit.

from __future__ import annotations

import base64
import json
from typing import Any

from .._transport._interface import Transport
from ..types import chronicle as _types


class ChronicleNamespace:
    """Chronicle — Structured audit event engine"""

    def __init__(self, transport: Transport, engine: str = "chronicle") -> None:
        self._transport = transport
        self._engine = engine

    async def actors(self, filter_args: str | None = None) -> _types.ChronicleActorsResponse:
        """ACTORS — Top 20 actors by event count in the given time window"""
        args: list[str] = ["ACTORS"]
        if filter_args is not None:
            args.append("FILTER_ARGS")
            args.append(str(filter_args))
        result = await self._transport.execute(self._engine, args)
        return _types.ChronicleActorsResponse(actors=result.get("actors", None), status=result.get("status", ""))

    async def auth(self, token: str) -> _types.ChronicleAuthResponse:
        """AUTH — Authenticate this connection"""
        args: list[str] = ["AUTH"]
        args.append(str(token))
        result = await self._transport.execute(self._engine, args)
        return _types.ChronicleAuthResponse(status=result.get("status", ""))

    async def command_list(self) -> _types.ChronicleCommandListResponse:
        """COMMAND LIST — List available commands"""
        args: list[str] = ["COMMAND", "LIST"]
        result = await self._transport.execute(self._engine, args)
        return _types.ChronicleCommandListResponse(commands=result.get("commands", None))

    async def count(self, filter_args: str | None = None) -> _types.ChronicleCountResponse:
        """COUNT — Count events matching filter predicates"""
        args: list[str] = ["COUNT"]
        if filter_args is not None:
            args.append("FILTER_ARGS")
            args.append(str(filter_args))
        result = await self._transport.execute(self._engine, args)
        return _types.ChronicleCountResponse(
            count=result.get("count", 0),
            scanned=result.get("scanned", 0),
            status=result.get("status", ""),
        )

    async def errors(self, filter_args: str | None = None) -> _types.ChronicleErrorsResponse:
        """ERRORS — Operations ranked by error rate in the given time window"""
        args: list[str] = ["ERRORS"]
        if filter_args is not None:
            args.append("FILTER_ARGS")
            args.append(str(filter_args))
        result = await self._transport.execute(self._engine, args)
        return _types.ChronicleErrorsResponse(errors=result.get("errors", None), status=result.get("status", ""))

    async def health(self) -> _types.ChronicleHealthResponse:
        """HEALTH — Health check"""
        args: list[str] = ["HEALTH"]
        result = await self._transport.execute(self._engine, args)
        return _types.ChronicleHealthResponse(events=result.get("events", 0), status=result.get("status", ""))

    async def hello(self) -> _types.ChronicleHelloResponse:
        """HELLO — Engine identity handshake — returns engine name, version, wire protocol, supported commands, and capability tags. Pre-auth; clients issue this on connect to verify they are talking to the expected engine and version."""
        args: list[str] = ["HELLO"]
        result = await self._transport.execute(self._engine, args)
        return _types.ChronicleHelloResponse(
            capabilities=result.get("capabilities", None),
            commands=result.get("commands", None),
            engine=result.get("engine", ""),
            protocol=result.get("protocol", ""),
            version=result.get("version", ""),
        )

    async def hotspots(self, filter_args: str | None = None) -> _types.ChronicleHotspotsResponse:
        """HOTSPOTS — Top 20 resources by access count in the given time window"""
        args: list[str] = ["HOTSPOTS"]
        if filter_args is not None:
            args.append("FILTER_ARGS")
            args.append(str(filter_args))
        result = await self._transport.execute(self._engine, args)
        return _types.ChronicleHotspotsResponse(hotspots=result.get("hotspots", None), status=result.get("status", ""))

    async def ingest(self, event_json: dict[str, Any]) -> _types.ChronicleIngestResponse:
        """INGEST — Ingest a single structured audit event"""
        args: list[str] = ["INGEST"]
        args.append(event_json if isinstance(event_json, str) else json.dumps(event_json))
        result = await self._transport.execute(self._engine, args)
        return _types.ChronicleIngestResponse(status=result.get("status", ""))

    async def ingest_batch(self, events_json: dict[str, Any]) -> _types.ChronicleIngestBatchResponse:
        """INGEST_BATCH — Ingest multiple events in a single call"""
        args: list[str] = ["INGEST_BATCH"]
        args.append(events_json if isinstance(events_json, str) else json.dumps(events_json))
        result = await self._transport.execute(self._engine, args)
        return _types.ChronicleIngestBatchResponse(ingested=result.get("ingested", 0), status=result.get("status", ""))

    async def ping(self) -> dict[str, Any]:
        """PING — Keepalive"""
        args: list[str] = ["PING"]
        result = await self._transport.execute(self._engine, args)
        return result

    async def query(self, filter_args: str | None = None) -> _types.ChronicleQueryResponse:
        """QUERY — Query events with filter predicates"""
        args: list[str] = ["QUERY"]
        if filter_args is not None:
            args.append("FILTER_ARGS")
            args.append(str(filter_args))
        result = await self._transport.execute(self._engine, args)
        return _types.ChronicleQueryResponse(
            events=result.get("events", None),
            matched=result.get("matched", 0),
            scanned=result.get("scanned", 0),
            status=result.get("status", ""),
        )

    async def verify(self) -> _types.ChronicleVerifyResponse:
        """VERIFY — Verify the cryptographic hash chain integrity of all events. Returns per-tenant and aggregate verified counts or an error if tampering is detected."""
        args: list[str] = ["VERIFY"]
        result = await self._transport.execute(self._engine, args)
        return _types.ChronicleVerifyResponse(
            per_tenant=result.get("per_tenant", None),
            status=result.get("status", ""),
            total=result.get("total", 0),
            verified=result.get("verified", 0),
        )
