# Auto-generated by shroudb-codegen. Do not edit.

from __future__ import annotations

import json
from typing import Any

from .._transport._interface import Transport
from ..types import cipher as _types


class CipherNamespace:
    """Cipher — Encryption-as-a-service"""

    def __init__(self, transport: Transport, engine: str = "cipher") -> None:
        self._transport = transport
        self._engine = engine

    async def auth(self, token: str) -> _types.CipherAuthResponse:
        """AUTH — Authenticate the connection"""
        args: list[str] = ["AUTH"]
        args.append(str(token))
        result = await self._transport.execute(self._engine, args)
        return _types.CipherAuthResponse(status=result.get("status", ""))

    async def command_list(self) -> _types.CipherCommandListResponse:
        """COMMAND LIST — List all supported commands"""
        args: list[str] = ["COMMAND", "LIST"]
        result = await self._transport.execute(self._engine, args)
        return _types.CipherCommandListResponse(count=result.get("count", 0), commands=result.get("commands", None))

    async def decrypt(self, keyring: str, ciphertext: str, context: str | None = None) -> _types.CipherDecryptResponse:
        """DECRYPT — Decrypt ciphertext using the embedded key version"""
        args: list[str] = ["DECRYPT"]
        args.append(str(keyring))
        args.append(str(ciphertext))
        if context is not None:
            args.append("CONTEXT")
            args.append(str(context))
        result = await self._transport.execute(self._engine, args)
        return _types.CipherDecryptResponse(plaintext=result.get("plaintext", ""))

    async def encrypt(self, keyring: str, plaintext: str, context: str | None = None, key_version: int | None = None, convergent: bool = False) -> _types.CipherEncryptResponse:
        """ENCRYPT — Encrypt plaintext with the active key version"""
        args: list[str] = ["ENCRYPT"]
        args.append(str(keyring))
        args.append(str(plaintext))
        if context is not None:
            args.append("CONTEXT")
            args.append(str(context))
        if key_version is not None:
            args.append("KEY_VERSION")
            args.append(str(key_version))
        if convergent:
            args.append("CONVERGENT")
        result = await self._transport.execute(self._engine, args)
        return _types.CipherEncryptResponse(ciphertext=result.get("ciphertext", ""), key_version=result.get("key_version", 0))

    async def generate_data_key(self, keyring: str, bits: int | None = None) -> _types.CipherGenerateDataKeyResponse:
        """GENERATE_DATA_KEY — Generate a data encryption key (envelope encryption pattern)"""
        args: list[str] = ["GENERATE_DATA_KEY"]
        args.append(str(keyring))
        if bits is not None:
            args.append("BITS")
            args.append(str(bits))
        result = await self._transport.execute(self._engine, args)
        return _types.CipherGenerateDataKeyResponse(
            plaintext_key=result.get("plaintext_key", ""),
            wrapped_key=result.get("wrapped_key", ""),
            key_version=result.get("key_version", 0),
        )

    async def health(self) -> _types.CipherHealthResponse:
        """HEALTH — Check server health"""
        args: list[str] = ["HEALTH"]
        result = await self._transport.execute(self._engine, args)
        return _types.CipherHealthResponse(status=result.get("status", ""))

    async def key_info(self, keyring: str) -> _types.CipherKeyInfoResponse:
        """KEY_INFO — Get keyring metadata and key version information"""
        args: list[str] = ["KEY_INFO"]
        args.append(str(keyring))
        result = await self._transport.execute(self._engine, args)
        return _types.CipherKeyInfoResponse(
            keyring=result.get("keyring", ""),
            algorithm=result.get("algorithm", None),
            active_version=result.get("active_version", 0),
            versions=result.get("versions", None),
        )

    async def keyring_create(self, name: str, algorithm: str, rotation_days: int | None = None, drain_days: int | None = None, convergent: bool = False) -> _types.CipherKeyringCreateResponse:
        """KEYRING CREATE — Create a new keyring with its first active key"""
        args: list[str] = ["KEYRING", "CREATE"]
        args.append(str(name))
        args.append(str(algorithm))
        if rotation_days is not None:
            args.append("ROTATION_DAYS")
            args.append(str(rotation_days))
        if drain_days is not None:
            args.append("DRAIN_DAYS")
            args.append(str(drain_days))
        if convergent:
            args.append("CONVERGENT")
        result = await self._transport.execute(self._engine, args)
        return _types.CipherKeyringCreateResponse(
            keyring=result.get("keyring", ""),
            algorithm=result.get("algorithm", None),
            active_version=result.get("active_version", 0),
        )

    async def keyring_list(self) -> _types.CipherKeyringListResponse:
        """KEYRING LIST — List all keyring names"""
        args: list[str] = ["KEYRING", "LIST"]
        result = await self._transport.execute(self._engine, args)
        return _types.CipherKeyringListResponse(keyrings=result.get("keyrings", None))

    async def ping(self) -> _types.CipherPingResponse:
        """PING — Simple connectivity check — returns PONG"""
        args: list[str] = ["PING"]
        result = await self._transport.execute(self._engine, args)
        return _types.CipherPingResponse(message=result.get("message", ""))

    async def rewrap(self, keyring: str, ciphertext: str, context: str | None = None) -> _types.CipherRewrapResponse:
        """REWRAP — Re-encrypt ciphertext with the current active key version"""
        args: list[str] = ["REWRAP"]
        args.append(str(keyring))
        args.append(str(ciphertext))
        if context is not None:
            args.append("CONTEXT")
            args.append(str(context))
        result = await self._transport.execute(self._engine, args)
        return _types.CipherRewrapResponse(ciphertext=result.get("ciphertext", ""), key_version=result.get("key_version", 0))

    async def rotate(self, keyring: str, force: bool = False, dryrun: bool = False) -> _types.CipherRotateResponse:
        """ROTATE — Rotate the keyring to a new key version"""
        args: list[str] = ["ROTATE"]
        args.append(str(keyring))
        if force:
            args.append("FORCE")
        if dryrun:
            args.append("DRYRUN")
        result = await self._transport.execute(self._engine, args)
        return _types.CipherRotateResponse(
            rotated=result.get("rotated", False),
            key_version=result.get("key_version", 0),
            previous_version=result.get("previous_version"),
        )

    async def sign(self, keyring: str, data: str) -> _types.CipherSignResponse:
        """SIGN — Create a detached signature"""
        args: list[str] = ["SIGN"]
        args.append(str(keyring))
        args.append(str(data))
        result = await self._transport.execute(self._engine, args)
        return _types.CipherSignResponse(signature=result.get("signature", ""), key_version=result.get("key_version", 0))

    async def verify_signature(self, keyring: str, data: str, signature: str) -> _types.CipherVerifySignatureResponse:
        """VERIFY_SIGNATURE — Verify a detached signature"""
        args: list[str] = ["VERIFY_SIGNATURE"]
        args.append(str(keyring))
        args.append(str(data))
        args.append(str(signature))
        result = await self._transport.execute(self._engine, args)
        return _types.CipherVerifySignatureResponse(valid=result.get("valid", False))
