# Auto-generated by shroudb-codegen. Do not edit.

from __future__ import annotations

import base64
import json
from typing import Any

from .._transport._interface import Transport
from ..types import courier as _types


class CourierNamespace:
    """Courier — Just-in-time decryption delivery engine"""

    def __init__(self, transport: Transport, engine: str = "courier") -> None:
        self._transport = transport
        self._engine = engine

    async def auth(self, token: str) -> _types.CourierAuthResponse:
        """AUTH — Authenticate the connection with a token"""
        args: list[str] = ["AUTH"]
        args.append(str(token))
        result = await self._transport.execute(self._engine, args)
        return _types.CourierAuthResponse(status=result.get("status", ""))

    async def channel_create(self, name: str, type_: str, config_json: str) -> _types.CourierChannelCreateResponse:
        """CHANNEL CREATE — Create a delivery channel"""
        args: list[str] = ["CHANNEL", "CREATE"]
        args.append(str(name))
        args.append(str(type_))
        args.append(str(config_json))
        result = await self._transport.execute(self._engine, args)
        return _types.CourierChannelCreateResponse(
            channel_type=result.get("channel_type", ""),
            name=result.get("name", ""),
            status=result.get("status", ""),
        )

    async def channel_delete(self, name: str) -> _types.CourierChannelDeleteResponse:
        """CHANNEL DELETE — Delete a channel"""
        args: list[str] = ["CHANNEL", "DELETE"]
        args.append(str(name))
        result = await self._transport.execute(self._engine, args)
        return _types.CourierChannelDeleteResponse(name=result.get("name", ""), status=result.get("status", ""))

    async def channel_get(self, name: str) -> _types.CourierChannelGetResponse:
        """CHANNEL GET — Get channel configuration"""
        args: list[str] = ["CHANNEL", "GET"]
        args.append(str(name))
        result = await self._transport.execute(self._engine, args)
        return _types.CourierChannelGetResponse(
            channel_type=result.get("channel_type", ""),
            created_at=result.get("created_at", 0),
            enabled=result.get("enabled", False),
            name=result.get("name", ""),
        )

    async def channel_list(self) -> _types.CourierChannelListResponse:
        """CHANNEL LIST — List all channels"""
        args: list[str] = ["CHANNEL", "LIST"]
        result = await self._transport.execute(self._engine, args)
        return _types.CourierChannelListResponse(
            channels=result.get("channels", None),
            count=result.get("count", 0),
            status=result.get("status", ""),
        )

    async def command_list(self) -> _types.CourierCommandListResponse:
        """COMMAND LIST — List available commands"""
        args: list[str] = ["COMMAND", "LIST"]
        result = await self._transport.execute(self._engine, args)
        return _types.CourierCommandListResponse(commands=result.get("commands", None), count=result.get("count", 0))

    async def deliver(self, json_data: str) -> _types.CourierDeliverResponse:
        """DELIVER — Decrypt recipient and deliver a message"""
        args: list[str] = ["DELIVER"]
        args.append(str(json_data))
        result = await self._transport.execute(self._engine, args)
        return _types.CourierDeliverResponse(
            channel=result.get("channel", ""),
            delivered_at=result.get("delivered_at", 0),
            delivery_id=result.get("delivery_id", ""),
            status=result.get("status", ""),
        )

    async def delivery_get(self, id_: str) -> _types.CourierDeliveryGetResponse:
        """DELIVERY GET — Get a delivery receipt by ID"""
        args: list[str] = ["DELIVERY", "GET"]
        args.append(str(id_))
        result = await self._transport.execute(self._engine, args)
        return _types.CourierDeliveryGetResponse(
            channel=result.get("channel", ""),
            delivered_at=result.get("delivered_at", 0),
            delivery_id=result.get("delivery_id", ""),
            error=result.get("error", ""),
            status=result.get("status", ""),
        )

    async def delivery_list(self, channel: str | None = None, limit: int | None = None) -> _types.CourierDeliveryListResponse:
        """DELIVERY LIST — List delivery receipts, optionally filtered by channel"""
        args: list[str] = ["DELIVERY", "LIST"]
        if channel is not None:
            args.append("CHANNEL")
            args.append(str(channel))
        if limit is not None:
            args.append("LIMIT")
            args.append(str(limit))
        result = await self._transport.execute(self._engine, args)
        return _types.CourierDeliveryListResponse(
            count=result.get("count", 0),
            receipts=result.get("receipts", None),
            status=result.get("status", ""),
        )

    async def health(self) -> _types.CourierHealthResponse:
        """HEALTH — Server health check"""
        args: list[str] = ["HEALTH"]
        result = await self._transport.execute(self._engine, args)
        return _types.CourierHealthResponse(channels=result.get("channels", 0), status=result.get("status", ""))

    async def metrics(self) -> _types.CourierMetricsResponse:
        """METRICS — Get delivery metrics (total, success, failure counts, per-channel breakdown)"""
        args: list[str] = ["METRICS"]
        result = await self._transport.execute(self._engine, args)
        return _types.CourierMetricsResponse(
            delivered=result.get("delivered", 0),
            failed=result.get("failed", 0),
            per_channel=result.get("per_channel", None),
            total_deliveries=result.get("total_deliveries", 0),
        )

    async def notify_event(self, channel: str, subject: str, body: str) -> _types.CourierNotifyEventResponse:
        """NOTIFY_EVENT — Trigger a notification on a pre-configured channel (e.g. rotation/expiry alerts)"""
        args: list[str] = ["NOTIFY_EVENT"]
        args.append(str(channel))
        args.append(str(subject))
        args.append(str(body))
        result = await self._transport.execute(self._engine, args)
        return _types.CourierNotifyEventResponse(
            channel=result.get("channel", ""),
            delivered_at=result.get("delivered_at", 0),
            delivery_id=result.get("delivery_id", ""),
            status=result.get("status", ""),
        )

    async def ping(self) -> dict[str, Any]:
        """PING — Connectivity check"""
        args: list[str] = ["PING"]
        result = await self._transport.execute(self._engine, args)
        return result
