# Auto-generated by shroudb-codegen. Do not edit.

from __future__ import annotations

import base64
import json
from typing import Any

from .._transport._interface import Transport
from ..types import forge as _types


class ForgeNamespace:
    """Forge — Internal certificate authority engine"""

    def __init__(self, transport: Transport, engine: str = "forge") -> None:
        self._transport = transport
        self._engine = engine

    async def auth(self, token: str) -> _types.ForgeAuthResponse:
        """AUTH — Authenticate this connection with a token"""
        args: list[str] = ["AUTH"]
        args.append(str(token))
        result = await self._transport.execute(self._engine, args)
        return _types.ForgeAuthResponse(status=result.get("status", ""))

    async def ca_create(self, name: str, algorithm: str, subject: str, ttl_days: int | None = None, parent: str | None = None) -> _types.ForgeCaCreateResponse:
        """CA CREATE — Create a new Certificate Authority"""
        args: list[str] = ["CA", "CREATE"]
        args.append(str(name))
        args.append(str(algorithm))
        args.append("SUBJECT")
        args.append(str(subject))
        if ttl_days is not None:
            args.append("TTL_DAYS")
            args.append(str(ttl_days))
        if parent is not None:
            args.append("PARENT")
            args.append(str(parent))
        result = await self._transport.execute(self._engine, args)
        return _types.ForgeCaCreateResponse(
            active_version=result.get("active_version", 0),
            algorithm=result.get("algorithm", ""),
            name=result.get("name", ""),
            subject=result.get("subject", ""),
        )

    async def ca_export(self, name: str) -> _types.ForgeCaExportResponse:
        """CA EXPORT — Export the active CA certificate (PEM)"""
        args: list[str] = ["CA", "EXPORT"]
        args.append(str(name))
        result = await self._transport.execute(self._engine, args)
        return _types.ForgeCaExportResponse(certificate_pem=result.get("certificate_pem", ""))

    async def ca_info(self, name: str) -> _types.ForgeCaInfoResponse:
        """CA INFO — Get CA metadata and key version status"""
        args: list[str] = ["CA", "INFO"]
        args.append(str(name))
        result = await self._transport.execute(self._engine, args)
        return _types.ForgeCaInfoResponse(
            algorithm=result.get("algorithm", ""),
            key_versions=result.get("key_versions", None),
            name=result.get("name", ""),
            subject=result.get("subject", ""),
        )

    async def ca_list(self) -> _types.ForgeCaListResponse:
        """CA LIST — List all Certificate Authorities"""
        args: list[str] = ["CA", "LIST"]
        result = await self._transport.execute(self._engine, args)
        return _types.ForgeCaListResponse(cas=result.get("cas", None))

    async def ca_rotate(self, name: str, force: bool = False, dryrun: bool = False) -> _types.ForgeCaRotateResponse:
        """CA ROTATE — Rotate CA signing key"""
        args: list[str] = ["CA", "ROTATE"]
        args.append(str(name))
        if force:
            args.append("FORCE")
        if dryrun:
            args.append("DRYRUN")
        result = await self._transport.execute(self._engine, args)
        return _types.ForgeCaRotateResponse(
            key_version=result.get("key_version", 0),
            previous_version=result.get("previous_version", 0),
            rotated=result.get("rotated", False),
        )

    async def command(self) -> _types.ForgeCommandResponse:
        """COMMAND — List supported commands"""
        args: list[str] = ["COMMAND"]
        result = await self._transport.execute(self._engine, args)
        return _types.ForgeCommandResponse(commands=result.get("commands", None))

    async def config_get(self, key: str) -> _types.ForgeConfigGetResponse:
        """CONFIG GET — Get a runtime configuration value"""
        args: list[str] = ["CONFIG", "GET"]
        args.append(str(key))
        result = await self._transport.execute(self._engine, args)
        return _types.ForgeConfigGetResponse(
            key=result.get("key", ""),
            status=result.get("status", ""),
            value=result.get("value", None),
        )

    async def config_set(self, key: str, value: str) -> _types.ForgeConfigSetResponse:
        """CONFIG SET — Set a runtime configuration value (only scheduler_interval_secs is mutable)"""
        args: list[str] = ["CONFIG", "SET"]
        args.append(str(key))
        args.append(str(value))
        result = await self._transport.execute(self._engine, args)
        return _types.ForgeConfigSetResponse(
            key=result.get("key", ""),
            status=result.get("status", ""),
            value=result.get("value", ""),
        )

    async def health(self) -> _types.ForgeHealthResponse:
        """HEALTH — Health check"""
        args: list[str] = ["HEALTH"]
        result = await self._transport.execute(self._engine, args)
        return _types.ForgeHealthResponse(status=result.get("status", ""))

    async def inspect(self, ca: str, serial: str) -> _types.ForgeInspectResponse:
        """INSPECT — Get certificate details"""
        args: list[str] = ["INSPECT"]
        args.append(str(ca))
        args.append(str(serial))
        result = await self._transport.execute(self._engine, args)
        return _types.ForgeInspectResponse(
            certificate_pem=result.get("certificate_pem", ""),
            serial=result.get("serial", ""),
            state=result.get("state", ""),
            subject=result.get("subject", ""),
        )

    async def issue(self, ca: str, subject: str, profile: str, ttl: str | None = None, san_dns: str | None = None, san_ip: str | None = None) -> _types.ForgeIssueResponse:
        """ISSUE — Issue a new certificate. Returns cert + private key (private key never stored)."""
        args: list[str] = ["ISSUE"]
        args.append(str(ca))
        args.append(str(subject))
        args.append(str(profile))
        if ttl is not None:
            args.append("TTL")
            args.append(str(ttl))
        if san_dns is not None:
            args.append("SAN_DNS")
            args.append(str(san_dns))
        if san_ip is not None:
            args.append("SAN_IP")
            args.append(str(san_ip))
        result = await self._transport.execute(self._engine, args)
        return _types.ForgeIssueResponse(
            certificate_pem=result.get("certificate_pem", ""),
            private_key_pem=result.get("private_key_pem", ""),
            serial=result.get("serial", ""),
        )

    async def issue_from_csr(self, ca: str, csr_pem: str, profile: str, ttl: str | None = None) -> _types.ForgeIssueFromCsrResponse:
        """ISSUE_FROM_CSR — Issue a certificate from a PEM-encoded CSR"""
        args: list[str] = ["ISSUE_FROM_CSR"]
        args.append(str(ca))
        args.append(str(csr_pem))
        args.append(str(profile))
        if ttl is not None:
            args.append("TTL")
            args.append(str(ttl))
        result = await self._transport.execute(self._engine, args)
        return _types.ForgeIssueFromCsrResponse(certificate_pem=result.get("certificate_pem", ""), serial=result.get("serial", ""))

    async def list_certs(self, ca: str, state: str | None = None, limit: int | None = None, offset: int | None = None) -> _types.ForgeListCertsResponse:
        """LIST_CERTS — List certificates for a CA"""
        args: list[str] = ["LIST_CERTS"]
        args.append(str(ca))
        if state is not None:
            args.append("STATE")
            args.append(str(state))
        if limit is not None:
            args.append("LIMIT")
            args.append(str(limit))
        if offset is not None:
            args.append("OFFSET")
            args.append(str(offset))
        result = await self._transport.execute(self._engine, args)
        return _types.ForgeListCertsResponse(certs=result.get("certs", None), count=result.get("count", 0))

    async def ping(self) -> _types.ForgePingResponse:
        """PING — Liveness probe. Returns PONG."""
        args: list[str] = ["PING"]
        result = await self._transport.execute(self._engine, args)
        return _types.ForgePingResponse(status=result.get("status", ""))

    async def regenerate_crl(self, ca: str) -> _types.ForgeRegenerateCrlResponse:
        """REGENERATE_CRL — Force regeneration of the CRL for a CA. Also accepted as `CA REGENERATE_CRL <name>`."""
        args: list[str] = ["REGENERATE_CRL"]
        args.append(str(ca))
        result = await self._transport.execute(self._engine, args)
        return _types.ForgeRegenerateCrlResponse(status=result.get("status", ""))

    async def renew(self, ca: str, serial: str, ttl: str | None = None) -> _types.ForgeRenewResponse:
        """RENEW — Renew a certificate (re-issue with same profile and SANs)"""
        args: list[str] = ["RENEW"]
        args.append(str(ca))
        args.append(str(serial))
        if ttl is not None:
            args.append("TTL")
            args.append(str(ttl))
        result = await self._transport.execute(self._engine, args)
        return _types.ForgeRenewResponse(
            certificate_pem=result.get("certificate_pem", ""),
            private_key_pem=result.get("private_key_pem", ""),
            serial=result.get("serial", ""),
        )

    async def revoke(self, ca: str, serial: str, reason: str | None = None) -> _types.ForgeRevokeResponse:
        """REVOKE — Revoke a certificate"""
        args: list[str] = ["REVOKE"]
        args.append(str(ca))
        args.append(str(serial))
        if reason is not None:
            args.append("REASON")
            args.append(str(reason))
        result = await self._transport.execute(self._engine, args)
        return _types.ForgeRevokeResponse(status=result.get("status", ""))
