# Auto-generated by shroudb-codegen. Do not edit.

from __future__ import annotations

import base64
import json
from typing import Any

from .._transport._interface import Transport
from ..types import keep as _types


class KeepNamespace:
    """Keep — Secrets manager with path-based access control and versioning"""

    def __init__(self, transport: Transport, engine: str = "keep") -> None:
        self._transport = transport
        self._engine = engine

    async def auth(self, token: str) -> _types.KeepAuthResponse:
        """AUTH — Authenticate this connection with a token."""
        args: list[str] = ["AUTH"]
        args.append(str(token))
        result = await self._transport.execute(self._engine, args)
        return _types.KeepAuthResponse(status=result.get("status", ""))

    async def command_list(self) -> _types.KeepCommandListResponse:
        """COMMAND LIST — List all supported commands."""
        args: list[str] = ["COMMAND", "LIST"]
        result = await self._transport.execute(self._engine, args)
        return _types.KeepCommandListResponse(count=result.get("count", 0), commands=result.get("commands", None))

    async def delete(self, path: str) -> _types.KeepDeleteResponse:
        """DELETE — Soft-delete a secret. Version history is preserved."""
        args: list[str] = ["DELETE"]
        args.append(str(path))
        result = await self._transport.execute(self._engine, args)
        return _types.KeepDeleteResponse(
            status=result.get("status", ""),
            path=result.get("path", None),
            deleted_at=result.get("deleted_at", 0),
        )

    async def get(self, path: str, version: str | None = None) -> _types.KeepGetResponse:
        """GET — Retrieve a secret value. Returns the latest version by default."""
        args: list[str] = ["GET"]
        args.append(str(path))
        if version is not None:
            args.append("VERSION")
            args.append(str(version))
        result = await self._transport.execute(self._engine, args)
        return _types.KeepGetResponse(
            status=result.get("status", ""),
            path=result.get("path", None),
            version=result.get("version", None),
            value=result.get("value", None),
            created_at=result.get("created_at", 0),
            created_by=result.get("created_by", ""),
        )

    async def get_many(
        self,
        calls: list[dict[str, Any]],
    ) -> list[_types.KeepGetResponse]:
        """GET — batch variant: pipelines N independent calls over one connection (ordered, not atomic)."""
        args_list: list[list[str]] = []
        for call in calls:
            args: list[str] = ["GET"]
            args.append(str(call["path"]))
            if "version" in call:
                args.append("VERSION")
                args.append(str(call["version"]))
            args_list.append(args)
        results = await self._transport.execute_many(self._engine, args_list)
        return [_types.KeepGetResponse(status=r.get("status", ""), path=r.get("path", None), version=r.get("version", None), value=r.get("value", None), created_at=r.get("created_at", 0), created_by=r.get("created_by", "")) for r in results]

    async def health(self) -> _types.KeepHealthResponse:
        """HEALTH — Health check."""
        args: list[str] = ["HEALTH"]
        result = await self._transport.execute(self._engine, args)
        return _types.KeepHealthResponse(status=result.get("status", ""))

    async def hello(self) -> _types.KeepHelloResponse:
        """HELLO — Engine identity handshake — returns engine name, version, wire protocol, supported commands, and capability tags. Pre-auth; clients issue this on connect to verify they are talking to the expected engine and version."""
        args: list[str] = ["HELLO"]
        result = await self._transport.execute(self._engine, args)
        return _types.KeepHelloResponse(
            engine=result.get("engine", ""),
            version=result.get("version", ""),
            protocol=result.get("protocol", ""),
            commands=result.get("commands", None),
            capabilities=result.get("capabilities", None),
        )

    async def list(self, prefix: str | None = None) -> _types.KeepListResponse:
        """LIST — List secret paths, optionally filtered by prefix. Excludes deleted secrets."""
        args: list[str] = ["LIST"]
        if prefix is not None:
            args.append(str(prefix))
        result = await self._transport.execute(self._engine, args)
        return _types.KeepListResponse(
            status=result.get("status", ""),
            count=result.get("count", 0),
            paths=result.get("paths", None),
        )

    async def ping(self) -> dict[str, Any]:
        """PING — Ping-pong."""
        args: list[str] = ["PING"]
        result = await self._transport.execute(self._engine, args)
        return result

    async def purge(self, path: str) -> _types.KeepPurgeResponse:
        """PURGE — Permanently remove a secret and all its versions. Irreversible — used for GDPR right-to-erasure compliance. After purge, GET returns not-found (not deleted)."""
        args: list[str] = ["PURGE"]
        args.append(str(path))
        result = await self._transport.execute(self._engine, args)
        return _types.KeepPurgeResponse(
            status=result.get("status", ""),
            path=result.get("path", None),
            purged_at=result.get("purged_at", None),
        )

    async def put(self, path: str, value: str | bytes) -> _types.KeepPutResponse:
        """PUT — Store a new version of a secret. Creates the secret if it doesn't exist. Undeletes if soft-deleted."""
        args: list[str] = ["PUT"]
        args.append(str(path))
        args.append(value if isinstance(value, str) else base64.b64encode(value).decode())
        result = await self._transport.execute(self._engine, args)
        return _types.KeepPutResponse(
            status=result.get("status", ""),
            path=result.get("path", None),
            version=result.get("version", None),
        )

    async def rekey(self, new_key: str) -> _types.KeepRekeyResponse:
        """REKEY — Re-encrypt all secrets with a new master key. Iterates all secrets (including deleted ones), decrypts every version with the current master key, re-encrypts with the new key, and switches to the new key for all future operations."""
        args: list[str] = ["REKEY"]
        args.append(str(new_key))
        result = await self._transport.execute(self._engine, args)
        return _types.KeepRekeyResponse(
            status=result.get("status", ""),
            rekeyed_secrets=result.get("rekeyed_secrets", 0),
            rekeyed_versions=result.get("rekeyed_versions", 0),
        )

    async def rotate(self, path: str) -> _types.KeepRotateResponse:
        """ROTATE — Re-encrypt the latest version with a new nonce. Creates a new version with the same plaintext."""
        args: list[str] = ["ROTATE"]
        args.append(str(path))
        result = await self._transport.execute(self._engine, args)
        return _types.KeepRotateResponse(
            status=result.get("status", ""),
            path=result.get("path", None),
            version=result.get("version", None),
        )

    async def versions(self, path: str) -> _types.KeepVersionsResponse:
        """VERSIONS — Get version history for a secret. Includes deleted secrets."""
        args: list[str] = ["VERSIONS"]
        args.append(str(path))
        result = await self._transport.execute(self._engine, args)
        return _types.KeepVersionsResponse(
            status=result.get("status", ""),
            path=result.get("path", None),
            version_count=result.get("version_count", 0),
            versions=result.get("versions", None),
            deleted=result.get("deleted", False),
        )
