# Auto-generated by shroudb-codegen. Do not edit.

from __future__ import annotations

import base64
import json
from typing import Any

from .._transport._interface import Transport
from ..types import scroll as _types


class ScrollNamespace:
    """Scroll — Durable append-only event log with cursored readers and reader groups"""

    def __init__(self, transport: Transport, engine: str = "scroll") -> None:
        self._transport = transport
        self._engine = engine

    async def ack(self, log: str, group: str, offset: int) -> _types.ScrollAckResponse:
        """ACK — Acknowledge a pending entry. Idempotent."""
        args: list[str] = ["ACK"]
        args.append(str(log))
        args.append(str(group))
        args.append(str(offset))
        result = await self._transport.execute(self._engine, args)
        return _types.ScrollAckResponse(status=result.get("status", ""))

    async def append(self, log: str, payload_b64: str, headers: dict[str, Any] | None = None, ttl_ms: int | None = None) -> _types.ScrollAppendResponse:
        """APPEND — Append an entry to a log. Mints a monotonic offset through the per-log serializer and encrypts the entry with the per-log DEK."""
        args: list[str] = ["APPEND"]
        args.append(str(log))
        args.append(str(payload_b64))
        if headers is not None:
            args.append("HEADERS")
            args.append(headers if isinstance(headers, str) else json.dumps(headers))
        if ttl_ms is not None:
            args.append("TTL_MS")
            args.append(str(ttl_ms))
        result = await self._transport.execute(self._engine, args)
        return _types.ScrollAppendResponse(offset=result.get("offset", 0), status=result.get("status", ""))

    async def auth(self, token: str) -> _types.ScrollAuthResponse:
        """AUTH — Authenticate the connection. Consumed at the connection layer before dispatch."""
        args: list[str] = ["AUTH"]
        args.append(str(token))
        result = await self._transport.execute(self._engine, args)
        return _types.ScrollAuthResponse(status=result.get("status", ""))

    async def claim(self, log: str, group: str, reader_id: str, min_idle_ms: int) -> _types.ScrollClaimResponse:
        """CLAIM — Reassign stalled pending entries to a new reader. Entries whose delivery_count would cross max_delivery_count are moved to scroll.dlq instead."""
        args: list[str] = ["CLAIM"]
        args.append(str(log))
        args.append(str(group))
        args.append(str(reader_id))
        args.append(str(min_idle_ms))
        result = await self._transport.execute(self._engine, args)
        return _types.ScrollClaimResponse(claimed=result.get("claimed", None), status=result.get("status", ""))

    async def command_list(self) -> _types.ScrollCommandListResponse:
        """COMMAND LIST — List all supported commands with their syntax."""
        args: list[str] = ["COMMAND", "LIST"]
        result = await self._transport.execute(self._engine, args)
        return _types.ScrollCommandListResponse(commands=result.get("commands", None))

    async def create_group(self, log: str, group: str, start_offset: str) -> _types.ScrollCreateGroupResponse:
        """CREATE_GROUP — Create a reader group. start_offset = 'earliest' | '0' starts from offset 0; 'latest' | '-1' starts after the current tail."""
        args: list[str] = ["CREATE_GROUP"]
        args.append(str(log))
        args.append(str(group))
        args.append(str(start_offset))
        result = await self._transport.execute(self._engine, args)
        return _types.ScrollCreateGroupResponse(status=result.get("status", ""))

    async def delete_group(self, log: str, group: str) -> _types.ScrollDeleteGroupResponse:
        """DELETE_GROUP — Tear down a single reader group: delete every pending record, then remove the group row. Counterpart to CREATE_GROUP; doesn't touch scroll.logs or the DEK, so other groups on the same log keep operating. Returns 'group not found' when the target doesn't exist."""
        args: list[str] = ["DELETE_GROUP"]
        args.append(str(log))
        args.append(str(group))
        result = await self._transport.execute(self._engine, args)
        return _types.ScrollDeleteGroupResponse(status=result.get("status", ""))

    async def delete_log(self, log: str) -> _types.ScrollDeleteLogResponse:
        """DELETE_LOG — Hard-delete all log state (entries, groups, pending, offset counter) and destroy the wrapped DEK to crypto-shred."""
        args: list[str] = ["DELETE_LOG"]
        args.append(str(log))
        result = await self._transport.execute(self._engine, args)
        return _types.ScrollDeleteLogResponse(status=result.get("status", ""))

    async def group_info(self, log: str, group: str) -> _types.ScrollGroupInfoResponse:
        """GROUP_INFO — Stats for a reader group: cursor, members, and pending entry count."""
        args: list[str] = ["GROUP_INFO"]
        args.append(str(log))
        args.append(str(group))
        result = await self._transport.execute(self._engine, args)
        return _types.ScrollGroupInfoResponse(
            created_at_ms=result.get("created_at_ms", 0),
            group=result.get("group", ""),
            last_delivered_offset=result.get("last_delivered_offset", 0),
            log=result.get("log", ""),
            members=result.get("members", None),
            pending_count=result.get("pending_count", 0),
        )

    async def health(self) -> _types.ScrollHealthResponse:
        """HEALTH — Engine liveness probe."""
        args: list[str] = ["HEALTH"]
        result = await self._transport.execute(self._engine, args)
        return _types.ScrollHealthResponse(status=result.get("status", ""))

    async def hello(self) -> _types.ScrollHelloResponse:
        """HELLO — Engine identity + version + supported commands. Pre-auth version-detection handshake."""
        args: list[str] = ["HELLO"]
        result = await self._transport.execute(self._engine, args)
        return _types.ScrollHelloResponse(
            capabilities=result.get("capabilities", None),
            commands=result.get("commands", None),
            engine=result.get("engine", ""),
            protocol=result.get("protocol", ""),
            version=result.get("version", ""),
        )

    async def log_info(self, log: str) -> _types.ScrollLogInfoResponse:
        """LOG_INFO — Stats for a log: entries minted, latest offset, created-at, and list of reader groups."""
        args: list[str] = ["LOG_INFO"]
        args.append(str(log))
        result = await self._transport.execute(self._engine, args)
        return _types.ScrollLogInfoResponse(
            created_at_ms=result.get("created_at_ms", 0),
            entries_minted=result.get("entries_minted", 0),
            groups=result.get("groups", None),
            latest_offset=result.get("latest_offset", None),
            log=result.get("log", ""),
        )

    async def ping(self) -> dict[str, Any]:
        """PING — Connection liveness probe. Returns PONG."""
        args: list[str] = ["PING"]
        result = await self._transport.execute(self._engine, args)
        return result

    async def read(self, log: str, from_offset: int, limit: int) -> _types.ScrollReadResponse:
        """READ — Range read starting at from_offset. Missing offsets (trimmed / TTL-expired) are skipped silently."""
        args: list[str] = ["READ"]
        args.append(str(log))
        args.append(str(from_offset))
        args.append(str(limit))
        result = await self._transport.execute(self._engine, args)
        return _types.ScrollReadResponse(entries=result.get("entries", None), status=result.get("status", ""))

    async def read_group(self, log: str, group: str, reader_id: str, limit: int) -> _types.ScrollReadGroupResponse:
        """READ_GROUP — Advance the group cursor under CAS on `scroll.groups`, register PendingEntry records, and return the decrypted batch."""
        args: list[str] = ["READ_GROUP"]
        args.append(str(log))
        args.append(str(group))
        args.append(str(reader_id))
        args.append(str(limit))
        result = await self._transport.execute(self._engine, args)
        return _types.ScrollReadGroupResponse(entries=result.get("entries", None), status=result.get("status", ""))

    async def replay(self, log: str, group: str, offset: int) -> _types.ScrollReplayResponse:
        """REPLAY — Move a DLQ entry back into a group's pending set. Preserves the original reader_id from the DLQ record, resets delivery_count to 1, stamps a fresh delivered_at_ms. Put-pending-first / delete-dlq-second ordering: a crash in-between leaves a duplicate, never a loss. Returns 'dlq entry not found' when the offset has no DLQ record, 'group not found' when the target group doesn't exist."""
        args: list[str] = ["REPLAY"]
        args.append(str(log))
        args.append(str(group))
        args.append(str(offset))
        result = await self._transport.execute(self._engine, args)
        return _types.ScrollReplayResponse(status=result.get("status", ""))

    async def tail(self, log: str, from_offset: int, limit: int, timeout_ms: int | None = None) -> _types.ScrollTailResponse:
        """TAIL — Live tail: returns at most limit entries at or after from_offset, waiting up to TIMEOUT ms (default 30_000) for new appends. Closes with TAIL_OVERFLOW on subscribe backpressure; client should fall back to READ."""
        args: list[str] = ["TAIL"]
        args.append(str(log))
        args.append(str(from_offset))
        args.append(str(limit))
        if timeout_ms is not None:
            args.append("TIMEOUT_MS")
            args.append(str(timeout_ms))
        result = await self._transport.execute(self._engine, args)
        return _types.ScrollTailResponse(entries=result.get("entries", None), status=result.get("status", ""))

    async def trim(self, log: str, selector: str, value: int) -> _types.ScrollTrimResponse:
        """TRIM — Explicit retention. MAX_LEN keeps the most recent N offsets; MAX_AGE drops entries whose appended_at_ms is older than now-ms."""
        args: list[str] = ["TRIM"]
        args.append(str(log))
        args.append("MAX_LEN")
        args.append(str(selector))
        args.append("TRIM")
        args.append(str(value))
        result = await self._transport.execute(self._engine, args)
        return _types.ScrollTrimResponse(deleted=result.get("deleted", 0), status=result.get("status", ""))
