# Auto-generated by shroudb-codegen. Do not edit.

from __future__ import annotations

import base64
import json
from typing import Any

from .._transport._interface import Transport
from ..types import sentry as _types


class SentryNamespace:
    """Sentry — Policy-based authorization engine"""

    def __init__(self, transport: Transport, engine: str = "sentry") -> None:
        self._transport = transport
        self._engine = engine

    async def auth(self, token: str) -> _types.SentryAuthResponse:
        """AUTH — Authenticate the connection with a token"""
        args: list[str] = ["AUTH"]
        args.append(str(token))
        result = await self._transport.execute(self._engine, args)
        return _types.SentryAuthResponse(status=result.get("status", ""))

    async def command_list(self) -> _types.SentryCommandListResponse:
        """COMMAND LIST — List all supported commands"""
        args: list[str] = ["COMMAND", "LIST"]
        result = await self._transport.execute(self._engine, args)
        return _types.SentryCommandListResponse(commands=result.get("commands", None), status=result.get("status", ""))

    async def evaluate(self, json_data: str) -> _types.SentryEvaluateResponse:
        """EVALUATE — Evaluate an authorization request against policies and return a signed decision"""
        args: list[str] = ["EVALUATE"]
        args.append(str(json_data))
        result = await self._transport.execute(self._engine, args)
        return _types.SentryEvaluateResponse(
            cache_until=result.get("cache_until", 0),
            decision=result.get("decision", ""),
            matched_policy=result.get("matched_policy", ""),
            status=result.get("status", ""),
            token=result.get("token", ""),
        )

    async def health(self) -> _types.SentryHealthResponse:
        """HEALTH — Server health check"""
        args: list[str] = ["HEALTH"]
        result = await self._transport.execute(self._engine, args)
        return _types.SentryHealthResponse(policy_count=result.get("policy_count", 0), status=result.get("status", ""))

    async def jwks(self) -> _types.SentryJwksResponse:
        """JWKS — Get the JSON Web Key Set for verifying decision tokens"""
        args: list[str] = ["JWKS"]
        result = await self._transport.execute(self._engine, args)
        return _types.SentryJwksResponse(keys=result.get("keys", None))

    async def key_info(self) -> _types.SentryKeyInfoResponse:
        """KEY INFO — Get signing key metadata"""
        args: list[str] = ["KEY", "INFO"]
        result = await self._transport.execute(self._engine, args)
        return _types.SentryKeyInfoResponse(
            active_kid=result.get("active_kid", ""),
            active_version=result.get("active_version", 0),
            algorithm=result.get("algorithm", ""),
            decision_ttl_secs=result.get("decision_ttl_secs", 0),
            drain_days=result.get("drain_days", 0),
            jwks_keys=result.get("jwks_keys", 0),
            rotation_days=result.get("rotation_days", 0),
            status=result.get("status", ""),
            total_versions=result.get("total_versions", 0),
        )

    async def key_rotate(self, force: bool = False, dryrun: bool = False) -> _types.SentryKeyRotateResponse:
        """KEY ROTATE — Rotate the signing key"""
        args: list[str] = ["KEY", "ROTATE"]
        if force:
            args.append("FORCE")
        if dryrun:
            args.append("DRYRUN")
        result = await self._transport.execute(self._engine, args)
        return _types.SentryKeyRotateResponse(
            key_version=result.get("key_version", 0),
            previous_version=result.get("previous_version", 0),
            rotated=result.get("rotated", False),
            status=result.get("status", ""),
        )

    async def ping(self) -> dict[str, Any]:
        """PING — Connectivity check"""
        args: list[str] = ["PING"]
        result = await self._transport.execute(self._engine, args)
        return result

    async def policy_create(self, name: str, json_data: str) -> _types.SentryPolicyCreateResponse:
        """POLICY CREATE — Create a new authorization policy"""
        args: list[str] = ["POLICY", "CREATE"]
        args.append(str(name))
        args.append(str(json_data))
        result = await self._transport.execute(self._engine, args)
        return _types.SentryPolicyCreateResponse(
            effect=result.get("effect", ""),
            name=result.get("name", ""),
            priority=result.get("priority", 0),
            status=result.get("status", ""),
            version=result.get("version", 0),
        )

    async def policy_delete(self, name: str) -> _types.SentryPolicyDeleteResponse:
        """POLICY DELETE — Delete a policy"""
        args: list[str] = ["POLICY", "DELETE"]
        args.append(str(name))
        result = await self._transport.execute(self._engine, args)
        return _types.SentryPolicyDeleteResponse(status=result.get("status", ""))

    async def policy_get(self, name: str) -> _types.SentryPolicyGetResponse:
        """POLICY GET — Get a policy by name"""
        args: list[str] = ["POLICY", "GET"]
        args.append(str(name))
        result = await self._transport.execute(self._engine, args)
        return _types.SentryPolicyGetResponse(
            action=result.get("action", None),
            conditions=result.get("conditions", None),
            created_at=result.get("created_at", 0),
            description=result.get("description", ""),
            effect=result.get("effect", ""),
            name=result.get("name", ""),
            principal=result.get("principal", None),
            priority=result.get("priority", 0),
            resource=result.get("resource", None),
            status=result.get("status", ""),
            updated_at=result.get("updated_at", 0),
            version=result.get("version", 0),
        )

    async def policy_history(self, name: str) -> _types.SentryPolicyHistoryResponse:
        """POLICY HISTORY — Get version history of a policy (all past versions plus current)"""
        args: list[str] = ["POLICY", "HISTORY"]
        args.append(str(name))
        result = await self._transport.execute(self._engine, args)
        return _types.SentryPolicyHistoryResponse(
            count=result.get("count", 0),
            name=result.get("name", ""),
            status=result.get("status", ""),
            versions=result.get("versions", None),
        )

    async def policy_list(self) -> _types.SentryPolicyListResponse:
        """POLICY LIST — List all policy names"""
        args: list[str] = ["POLICY", "LIST"]
        result = await self._transport.execute(self._engine, args)
        return _types.SentryPolicyListResponse(
            count=result.get("count", 0),
            policies=result.get("policies", None),
            status=result.get("status", ""),
        )

    async def policy_update(self, name: str, json_data: str) -> _types.SentryPolicyUpdateResponse:
        """POLICY UPDATE — Update an existing policy"""
        args: list[str] = ["POLICY", "UPDATE"]
        args.append(str(name))
        args.append(str(json_data))
        result = await self._transport.execute(self._engine, args)
        return _types.SentryPolicyUpdateResponse(
            effect=result.get("effect", ""),
            name=result.get("name", ""),
            priority=result.get("priority", 0),
            status=result.get("status", ""),
            updated_at=result.get("updated_at", 0),
            version=result.get("version", 0),
        )
