# Auto-generated by shroudb-codegen. Do not edit.

from __future__ import annotations

import base64
import json
from typing import Any

from .._transport._interface import Transport
from ..types import shroudb as _types


class ShroudbNamespace:
    """Shroudb — Encrypted key-value database"""

    def __init__(self, transport: Transport, engine: str = "shroudb") -> None:
        self._transport = transport
        self._engine = engine

    async def auth(self, token: str) -> _types.ShroudbAuthResponse:
        """AUTH — Authenticate the connection with a token"""
        args: list[str] = ["AUTH"]
        args.append(str(token))
        result = await self._transport.execute(self._engine, args)
        return _types.ShroudbAuthResponse(actor=result.get("actor", ""))

    async def command_list(self) -> _types.ShroudbCommandListResponse:
        """COMMAND LIST — List all supported commands"""
        args: list[str] = ["COMMAND", "LIST"]
        result = await self._transport.execute(self._engine, args)
        return _types.ShroudbCommandListResponse(commands=result.get("commands", None), count=result.get("count", 0))

    async def config_get(self, key: str) -> _types.ShroudbConfigGetResponse:
        """CONFIG GET — Read a runtime configuration value"""
        args: list[str] = ["CONFIG", "GET"]
        args.append(str(key))
        result = await self._transport.execute(self._engine, args)
        return _types.ShroudbConfigGetResponse(key=result.get("key", ""), value=result.get("value", None))

    async def config_set(self, key: str, value: str) -> dict[str, Any]:
        """CONFIG SET — Set a runtime configuration value (admin only)"""
        args: list[str] = ["CONFIG", "SET"]
        args.append(str(key))
        args.append(str(value))
        result = await self._transport.execute(self._engine, args)
        return result

    async def delete(self, namespace: str, key: str) -> _types.ShroudbDeleteResponse:
        """DELETE — Delete a key by writing a tombstone"""
        args: list[str] = ["DELETE"]
        args.append(str(namespace))
        args.append(str(key))
        result = await self._transport.execute(self._engine, args)
        return _types.ShroudbDeleteResponse(version=result.get("version", 0))

    async def get(self, namespace: str, key: str, meta: str | None = None, version: int | None = None) -> _types.ShroudbGetResponse:
        """GET — Retrieve the value at a key"""
        args: list[str] = ["GET"]
        args.append(str(namespace))
        args.append(str(key))
        if meta is not None:
            args.append(str(meta))
        if version is not None:
            args.append("VERSION")
            args.append(str(version))
        result = await self._transport.execute(self._engine, args)
        return _types.ShroudbGetResponse(
            key=result.get("key", None),
            metadata=result.get("metadata", None),
            value=result.get("value", None),
            version=result.get("version", 0),
        )

    async def health(self) -> _types.ShroudbHealthResponse:
        """HEALTH — Check server health"""
        args: list[str] = ["HEALTH"]
        result = await self._transport.execute(self._engine, args)
        return _types.ShroudbHealthResponse(message=result.get("message", ""))

    async def list(self, namespace: str, prefix: str | None = None, cursor: str | None = None, limit: int | None = None) -> _types.ShroudbListResponse:
        """LIST — List active keys in a namespace"""
        args: list[str] = ["LIST"]
        args.append(str(namespace))
        if prefix is not None:
            args.append("PREFIX")
            args.append(str(prefix))
        if cursor is not None:
            args.append("CURSOR")
            args.append(str(cursor))
        if limit is not None:
            args.append("LIMIT")
            args.append(str(limit))
        result = await self._transport.execute(self._engine, args)
        return _types.ShroudbListResponse(cursor=result.get("cursor", None), keys=result.get("keys", None))

    async def namespace_alter(self, name: str, schema: dict[str, Any] | None = None, max_versions: int | None = None, tombstone_retention: int | None = None) -> dict[str, Any]:
        """NAMESPACE ALTER — Update namespace configuration (enforce-on-write-only)"""
        args: list[str] = ["NAMESPACE", "ALTER"]
        args.append(str(name))
        if schema is not None:
            args.append("SCHEMA")
            args.append(schema if isinstance(schema, str) else json.dumps(schema))
        if max_versions is not None:
            args.append("MAX_VERSIONS")
            args.append(str(max_versions))
        if tombstone_retention is not None:
            args.append("TOMBSTONE_RETENTION")
            args.append(str(tombstone_retention))
        result = await self._transport.execute(self._engine, args)
        return result

    async def namespace_create(self, name: str, schema: dict[str, Any] | None = None, max_versions: int | None = None, tombstone_retention: int | None = None) -> dict[str, Any]:
        """NAMESPACE CREATE — Create a new namespace"""
        args: list[str] = ["NAMESPACE", "CREATE"]
        args.append(str(name))
        if schema is not None:
            args.append("SCHEMA")
            args.append(schema if isinstance(schema, str) else json.dumps(schema))
        if max_versions is not None:
            args.append("MAX_VERSIONS")
            args.append(str(max_versions))
        if tombstone_retention is not None:
            args.append("TOMBSTONE_RETENTION")
            args.append(str(tombstone_retention))
        result = await self._transport.execute(self._engine, args)
        return result

    async def namespace_drop(self, name: str, force: str | None = None) -> dict[str, Any]:
        """NAMESPACE DROP — Drop a namespace"""
        args: list[str] = ["NAMESPACE", "DROP"]
        args.append(str(name))
        if force is not None:
            args.append(str(force))
        result = await self._transport.execute(self._engine, args)
        return result

    async def namespace_info(self, name: str) -> _types.ShroudbNamespaceInfoResponse:
        """NAMESPACE INFO — Get metadata about a namespace"""
        args: list[str] = ["NAMESPACE", "INFO"]
        args.append(str(name))
        result = await self._transport.execute(self._engine, args)
        return _types.ShroudbNamespaceInfoResponse(
            created_at=result.get("created_at", 0),
            key_count=result.get("key_count", 0),
            name=result.get("name", ""),
        )

    async def namespace_list(self, cursor: str | None = None, limit: int | None = None) -> _types.ShroudbNamespaceListResponse:
        """NAMESPACE LIST — List namespaces (filtered by token grants)"""
        args: list[str] = ["NAMESPACE", "LIST"]
        if cursor is not None:
            args.append("CURSOR")
            args.append(str(cursor))
        if limit is not None:
            args.append("LIMIT")
            args.append(str(limit))
        result = await self._transport.execute(self._engine, args)
        return _types.ShroudbNamespaceListResponse(cursor=result.get("cursor", None), namespaces=result.get("namespaces", None))

    async def namespace_validate(self, name: str) -> _types.ShroudbNamespaceValidateResponse:
        """NAMESPACE VALIDATE — Check existing entries against current MetaSchema"""
        args: list[str] = ["NAMESPACE", "VALIDATE"]
        args.append(str(name))
        result = await self._transport.execute(self._engine, args)
        return _types.ShroudbNamespaceValidateResponse(count=result.get("count", 0), reports=result.get("reports", None))

    async def ping(self) -> _types.ShroudbPingResponse:
        """PING — Test connectivity"""
        args: list[str] = ["PING"]
        result = await self._transport.execute(self._engine, args)
        return _types.ShroudbPingResponse(message=result.get("message", ""))

    async def pipeline(self, count: int) -> dict[str, Any]:
        """PIPELINE — Execute commands atomically (all succeed or all roll back)"""
        args: list[str] = ["PIPELINE"]
        args.append(str(count))
        result = await self._transport.execute(self._engine, args)
        return result

    async def put(self, namespace: str, key: str, value: str | None = None, meta: dict[str, Any] | None = None) -> _types.ShroudbPutResponse:
        """PUT — Store a value at the given key. Auto-increments version."""
        args: list[str] = ["PUT"]
        args.append(str(namespace))
        args.append(str(key))
        if value is not None:
            args.append(str(value))
        if meta is not None:
            args.append("META")
            args.append(meta if isinstance(meta, str) else json.dumps(meta))
        result = await self._transport.execute(self._engine, args)
        return _types.ShroudbPutResponse(version=result.get("version", 0))

    async def subscribe(self, namespace: str, key: str | None = None, events: str | None = None) -> dict[str, Any]:
        """SUBSCRIBE — Subscribe to change events on a namespace"""
        args: list[str] = ["SUBSCRIBE"]
        args.append(str(namespace))
        if key is not None:
            args.append("KEY")
            args.append(str(key))
        if events is not None:
            args.append("EVENTS")
            args.append(str(events))
        result = await self._transport.execute(self._engine, args)
        return result

    async def unsubscribe(self) -> dict[str, Any]:
        """UNSUBSCRIBE — End the current subscription"""
        args: list[str] = ["UNSUBSCRIBE"]
        result = await self._transport.execute(self._engine, args)
        return result

    async def versions(self, namespace: str, key: str, limit: int | None = None, from_: int | None = None) -> _types.ShroudbVersionsResponse:
        """VERSIONS — Retrieve version history for a key (most recent first)"""
        args: list[str] = ["VERSIONS"]
        args.append(str(namespace))
        args.append(str(key))
        if limit is not None:
            args.append("LIMIT")
            args.append(str(limit))
        if from_ is not None:
            args.append("FROM")
            args.append(str(from_))
        result = await self._transport.execute(self._engine, args)
        return _types.ShroudbVersionsResponse(versions=result.get("versions", None))
