# Auto-generated by shroudb-codegen. Do not edit.

from __future__ import annotations

import base64
import json
from typing import Any

from .._transport._interface import Transport
from ..types import sigil as _types


class SigilNamespace:
    """Sigil — Schema-driven credential envelope engine"""

    def __init__(self, transport: Transport, engine: str = "sigil") -> None:
        self._transport = transport
        self._engine = engine

    async def auth(self, token: str) -> _types.SigilAuthResponse:
        """AUTH — Authenticate the current TCP connection with a bearer token. Handled at the connection layer, not dispatched to the engine. HTTP transport uses the Authorization: Bearer header instead."""
        args: list[str] = ["AUTH"]
        args.append(str(token))
        result = await self._transport.execute(self._engine, args)
        return _types.SigilAuthResponse(status=result.get("status", ""))

    async def credential_change(self, schema: str, id_: str, field: str, old: str, new: str) -> _types.SigilCredentialChangeResponse:
        """CREDENTIAL CHANGE — Change a credential field (requires old value for verification)"""
        args: list[str] = ["CREDENTIAL", "CHANGE"]
        args.append(str(schema))
        args.append(str(id_))
        args.append(str(field))
        args.append(str(old))
        args.append(str(new))
        result = await self._transport.execute(self._engine, args)
        return _types.SigilCredentialChangeResponse(status=result.get("status", ""))

    async def credential_import(self, schema: str, id_: str, field: str, hash_: str, meta: dict[str, Any] | None = None) -> _types.SigilCredentialImportResponse:
        """CREDENTIAL IMPORT — Import a pre-hashed credential (bcrypt, scrypt, argon2). Transparently rehashed to Argon2id on next verify."""
        args: list[str] = ["CREDENTIAL", "IMPORT"]
        args.append(str(schema))
        args.append(str(id_))
        args.append(str(field))
        args.append(str(hash_))
        if meta is not None:
            args.append("META")
            args.append(meta if isinstance(meta, str) else json.dumps(meta))
        result = await self._transport.execute(self._engine, args)
        return _types.SigilCredentialImportResponse(algorithm=result.get("algorithm", ""), status=result.get("status", ""))

    async def credential_reset(self, schema: str, id_: str, field: str, new: str) -> _types.SigilCredentialResetResponse:
        """CREDENTIAL RESET — Force-reset a credential field without requiring old value (admin/reset token)"""
        args: list[str] = ["CREDENTIAL", "RESET"]
        args.append(str(schema))
        args.append(str(id_))
        args.append(str(field))
        args.append(str(new))
        result = await self._transport.execute(self._engine, args)
        return _types.SigilCredentialResetResponse(status=result.get("status", ""))

    async def envelope_create(self, schema: str, id_: str, json_data: dict[str, Any]) -> _types.SigilEnvelopeCreateResponse:
        """ENVELOPE CREATE — Create an envelope with field routing per schema kind"""
        args: list[str] = ["ENVELOPE", "CREATE"]
        args.append(str(schema))
        args.append(str(id_))
        args.append(json_data if isinstance(json_data, str) else json.dumps(json_data))
        result = await self._transport.execute(self._engine, args)
        return _types.SigilEnvelopeCreateResponse(
            created_at=result.get("created_at", 0),
            entity_id=result.get("entity_id", ""),
            fields=result.get("fields", None),
            status=result.get("status", ""),
        )

    async def envelope_delete(self, schema: str, id_: str) -> _types.SigilEnvelopeDeleteResponse:
        """ENVELOPE DELETE — Delete an envelope and all associated data"""
        args: list[str] = ["ENVELOPE", "DELETE"]
        args.append(str(schema))
        args.append(str(id_))
        result = await self._transport.execute(self._engine, args)
        return _types.SigilEnvelopeDeleteResponse(status=result.get("status", ""))

    async def envelope_get(self, schema: str, id_: str) -> _types.SigilEnvelopeGetResponse:
        """ENVELOPE GET — Get an envelope record"""
        args: list[str] = ["ENVELOPE", "GET"]
        args.append(str(schema))
        args.append(str(id_))
        result = await self._transport.execute(self._engine, args)
        return _types.SigilEnvelopeGetResponse(
            created_at=result.get("created_at", 0),
            entity_id=result.get("entity_id", ""),
            fields=result.get("fields", None),
            updated_at=result.get("updated_at", 0),
        )

    async def envelope_import(self, schema: str, id_: str, json_data: dict[str, Any]) -> _types.SigilEnvelopeImportResponse:
        """ENVELOPE IMPORT — Import an envelope with pre-hashed credential fields. Non-credential fields processed normally."""
        args: list[str] = ["ENVELOPE", "IMPORT"]
        args.append(str(schema))
        args.append(str(id_))
        args.append(json_data if isinstance(json_data, str) else json.dumps(json_data))
        result = await self._transport.execute(self._engine, args)
        return _types.SigilEnvelopeImportResponse(
            created_at=result.get("created_at", 0),
            entity_id=result.get("entity_id", ""),
            fields=result.get("fields", None),
            status=result.get("status", ""),
        )

    async def envelope_lookup(self, schema: str, field: str, value: str) -> _types.SigilEnvelopeLookupResponse:
        """ENVELOPE LOOKUP — Look up an envelope by indexed or searchable field value. Returns the matched entity ID only."""
        args: list[str] = ["ENVELOPE", "LOOKUP"]
        args.append(str(schema))
        args.append(str(field))
        args.append(str(value))
        result = await self._transport.execute(self._engine, args)
        return _types.SigilEnvelopeLookupResponse(entity_id=result.get("entity_id", ""), status=result.get("status", ""))

    async def envelope_update(self, schema: str, id_: str, json_data: dict[str, Any]) -> _types.SigilEnvelopeUpdateResponse:
        """ENVELOPE UPDATE — Update non-credential fields on an existing envelope"""
        args: list[str] = ["ENVELOPE", "UPDATE"]
        args.append(str(schema))
        args.append(str(id_))
        args.append(json_data if isinstance(json_data, str) else json.dumps(json_data))
        result = await self._transport.execute(self._engine, args)
        return _types.SigilEnvelopeUpdateResponse(
            entity_id=result.get("entity_id", ""),
            fields=result.get("fields", None),
            status=result.get("status", ""),
            updated_at=result.get("updated_at", 0),
        )

    async def envelope_verify(self, schema: str, id_: str, field: str, value: str) -> _types.SigilEnvelopeVerifyResponse:
        """ENVELOPE VERIFY — Verify a credential field on an envelope by explicit field name"""
        args: list[str] = ["ENVELOPE", "VERIFY"]
        args.append(str(schema))
        args.append(str(id_))
        args.append(str(field))
        args.append(str(value))
        result = await self._transport.execute(self._engine, args)
        return _types.SigilEnvelopeVerifyResponse(status=result.get("status", ""), valid=result.get("valid", False))

    async def health(self) -> _types.SigilHealthResponse:
        """HEALTH — Health check"""
        args: list[str] = ["HEALTH"]
        result = await self._transport.execute(self._engine, args)
        return _types.SigilHealthResponse(status=result.get("status", ""))

    async def jwks(self, schema: str) -> dict[str, Any]:
        """JWKS — Get the JSON Web Key Set for external token verification"""
        args: list[str] = ["JWKS"]
        args.append(str(schema))
        result = await self._transport.execute(self._engine, args)
        return result

    async def password_change(self, schema: str, id_: str, old: str, new: str) -> _types.SigilPasswordChangeResponse:
        """PASSWORD CHANGE — Sugar: change password. Infers credential field from schema. Equivalent to CREDENTIAL CHANGE with implicit field."""
        args: list[str] = ["PASSWORD", "CHANGE"]
        args.append(str(schema))
        args.append(str(id_))
        args.append(str(old))
        args.append(str(new))
        result = await self._transport.execute(self._engine, args)
        return _types.SigilPasswordChangeResponse(status=result.get("status", ""))

    async def password_import(self, schema: str, id_: str, hash_: str, meta: dict[str, Any] | None = None) -> _types.SigilPasswordImportResponse:
        """PASSWORD IMPORT — Sugar: import pre-hashed password. Infers credential field from schema. Equivalent to CREDENTIAL IMPORT with implicit field."""
        args: list[str] = ["PASSWORD", "IMPORT"]
        args.append(str(schema))
        args.append(str(id_))
        args.append(str(hash_))
        if meta is not None:
            args.append("META")
            args.append(meta if isinstance(meta, str) else json.dumps(meta))
        result = await self._transport.execute(self._engine, args)
        return _types.SigilPasswordImportResponse(algorithm=result.get("algorithm", ""), status=result.get("status", ""))

    async def password_reset(self, schema: str, id_: str, new: str) -> _types.SigilPasswordResetResponse:
        """PASSWORD RESET — Sugar: force-reset password. Infers credential field from schema. Equivalent to CREDENTIAL RESET with implicit field."""
        args: list[str] = ["PASSWORD", "RESET"]
        args.append(str(schema))
        args.append(str(id_))
        args.append(str(new))
        result = await self._transport.execute(self._engine, args)
        return _types.SigilPasswordResetResponse(status=result.get("status", ""))

    async def ping(self) -> _types.SigilPingResponse:
        """PING — Ping-pong connectivity test"""
        args: list[str] = ["PING"]
        result = await self._transport.execute(self._engine, args)
        return _types.SigilPingResponse(status=result.get("status", ""))

    async def schema_alter(self, name: str, action: str, field_json: dict[str, Any] | None = None, field_name: str | None = None) -> _types.SigilSchemaAlterResponse:
        """SCHEMA ALTER — Add or remove fields from a schema, producing a new version. Added fields are optional (required=false). Existing envelopes remain readable."""
        args: list[str] = ["SCHEMA", "ALTER"]
        args.append(str(name))
        args.append("ADD")
        args.append(str(action))
        if field_json is not None:
            args.append("FIELD_JSON")
            args.append(field_json if isinstance(field_json, str) else json.dumps(field_json))
        if field_name is not None:
            args.append("FIELD_NAME")
            args.append(str(field_name))
        result = await self._transport.execute(self._engine, args)
        return _types.SigilSchemaAlterResponse(
            fields=result.get("fields", 0),
            name=result.get("name", ""),
            status=result.get("status", ""),
            version=result.get("version", 0),
        )

    async def schema_get(self, name: str) -> dict[str, Any]:
        """SCHEMA GET — Get a schema definition by name"""
        args: list[str] = ["SCHEMA", "GET"]
        args.append(str(name))
        result = await self._transport.execute(self._engine, args)
        return result

    async def schema_list(self) -> dict[str, Any]:
        """SCHEMA LIST — List all registered schema names"""
        args: list[str] = ["SCHEMA", "LIST"]
        result = await self._transport.execute(self._engine, args)
        return result

    async def schema_register(self, name: str, json_data: dict[str, Any]) -> _types.SigilSchemaRegisterResponse:
        """SCHEMA REGISTER — Register a credential envelope schema"""
        args: list[str] = ["SCHEMA", "REGISTER"]
        args.append(str(name))
        args.append(json_data if isinstance(json_data, str) else json.dumps(json_data))
        result = await self._transport.execute(self._engine, args)
        return _types.SigilSchemaRegisterResponse(status=result.get("status", ""), version=result.get("version", 0))

    async def session_create(self, schema: str, id_: str, password: str, meta: dict[str, Any] | None = None) -> _types.SigilSessionCreateResponse:
        """SESSION CREATE — Verify credentials and issue access + refresh tokens. Fields annotated with claim=true are auto-included in the JWT from the entity's envelope. Enriched claim values override caller-provided META for the same key."""
        args: list[str] = ["SESSION", "CREATE"]
        args.append(str(schema))
        args.append(str(id_))
        args.append(str(password))
        if meta is not None:
            args.append("META")
            args.append(meta if isinstance(meta, str) else json.dumps(meta))
        result = await self._transport.execute(self._engine, args)
        return _types.SigilSessionCreateResponse(
            access_token=result.get("access_token", ""),
            expires_in=result.get("expires_in", 0),
            refresh_token=result.get("refresh_token", ""),
            status=result.get("status", ""),
        )

    async def session_list(self, schema: str, id_: str) -> dict[str, Any]:
        """SESSION LIST — List active sessions for an entity"""
        args: list[str] = ["SESSION", "LIST"]
        args.append(str(schema))
        args.append(str(id_))
        result = await self._transport.execute(self._engine, args)
        return result

    async def session_login(self, schema: str, field: str, value: str, password: str, meta: dict[str, Any] | None = None) -> _types.SigilSessionLoginResponse:
        """SESSION LOGIN — Verify credentials by indexed field value (e.g., email) and issue access + refresh tokens. Same claim enrichment as SESSION CREATE."""
        args: list[str] = ["SESSION", "LOGIN"]
        args.append(str(schema))
        args.append(str(field))
        args.append(str(value))
        args.append(str(password))
        if meta is not None:
            args.append("META")
            args.append(meta if isinstance(meta, str) else json.dumps(meta))
        result = await self._transport.execute(self._engine, args)
        return _types.SigilSessionLoginResponse(
            access_token=result.get("access_token", ""),
            expires_in=result.get("expires_in", 0),
            refresh_token=result.get("refresh_token", ""),
            status=result.get("status", ""),
        )

    async def session_refresh(self, schema: str, token: str) -> _types.SigilSessionRefreshResponse:
        """SESSION REFRESH — Rotate refresh token and issue new access token. Fields annotated with claim=true are re-read from the entity's current envelope, so refreshed tokens reflect the latest values (e.g. role changes)."""
        args: list[str] = ["SESSION", "REFRESH"]
        args.append(str(schema))
        args.append(str(token))
        result = await self._transport.execute(self._engine, args)
        return _types.SigilSessionRefreshResponse(
            access_token=result.get("access_token", ""),
            expires_in=result.get("expires_in", 0),
            refresh_token=result.get("refresh_token", ""),
            status=result.get("status", ""),
        )

    async def session_revoke(self, schema: str, token: str) -> _types.SigilSessionRevokeResponse:
        """SESSION REVOKE — Revoke a single refresh token (logout one session)"""
        args: list[str] = ["SESSION", "REVOKE"]
        args.append(str(schema))
        args.append(str(token))
        result = await self._transport.execute(self._engine, args)
        return _types.SigilSessionRevokeResponse(status=result.get("status", ""))

    async def session_revoke_all(self, schema: str, id_: str) -> _types.SigilSessionRevokeAllResponse:
        """SESSION REVOKE ALL — Revoke all sessions for an entity (logout everywhere)"""
        args: list[str] = ["SESSION", "REVOKE ALL"]
        args.append(str(schema))
        args.append(str(id_))
        result = await self._transport.execute(self._engine, args)
        return _types.SigilSessionRevokeAllResponse(revoked=result.get("revoked", 0), status=result.get("status", ""))

    async def user_create(self, schema: str, id_: str, json_data: dict[str, Any]) -> _types.SigilUserCreateResponse:
        """USER CREATE — Sugar: create an envelope. Equivalent to ENVELOPE CREATE."""
        args: list[str] = ["USER", "CREATE"]
        args.append(str(schema))
        args.append(str(id_))
        args.append(json_data if isinstance(json_data, str) else json.dumps(json_data))
        result = await self._transport.execute(self._engine, args)
        return _types.SigilUserCreateResponse(
            created_at=result.get("created_at", 0),
            entity_id=result.get("entity_id", ""),
            fields=result.get("fields", None),
            status=result.get("status", ""),
        )

    async def user_delete(self, schema: str, id_: str) -> _types.SigilUserDeleteResponse:
        """USER DELETE — Sugar: delete an envelope. Equivalent to ENVELOPE DELETE."""
        args: list[str] = ["USER", "DELETE"]
        args.append(str(schema))
        args.append(str(id_))
        result = await self._transport.execute(self._engine, args)
        return _types.SigilUserDeleteResponse(status=result.get("status", ""))

    async def user_get(self, schema: str, id_: str) -> _types.SigilUserGetResponse:
        """USER GET — Sugar: get an envelope. Equivalent to ENVELOPE GET."""
        args: list[str] = ["USER", "GET"]
        args.append(str(schema))
        args.append(str(id_))
        result = await self._transport.execute(self._engine, args)
        return _types.SigilUserGetResponse(
            created_at=result.get("created_at", 0),
            entity_id=result.get("entity_id", ""),
            fields=result.get("fields", None),
            updated_at=result.get("updated_at", 0),
        )

    async def user_import(self, schema: str, id_: str, json_data: dict[str, Any]) -> _types.SigilUserImportResponse:
        """USER IMPORT — Sugar: import an envelope with pre-hashed credentials. Equivalent to ENVELOPE IMPORT."""
        args: list[str] = ["USER", "IMPORT"]
        args.append(str(schema))
        args.append(str(id_))
        args.append(json_data if isinstance(json_data, str) else json.dumps(json_data))
        result = await self._transport.execute(self._engine, args)
        return _types.SigilUserImportResponse(
            created_at=result.get("created_at", 0),
            entity_id=result.get("entity_id", ""),
            fields=result.get("fields", None),
            status=result.get("status", ""),
        )

    async def user_lookup(self, schema: str, field: str, value: str) -> _types.SigilUserLookupResponse:
        """USER LOOKUP — Sugar: look up by indexed or searchable field value. Equivalent to ENVELOPE LOOKUP."""
        args: list[str] = ["USER", "LOOKUP"]
        args.append(str(schema))
        args.append(str(field))
        args.append(str(value))
        result = await self._transport.execute(self._engine, args)
        return _types.SigilUserLookupResponse(entity_id=result.get("entity_id", ""), status=result.get("status", ""))

    async def user_update(self, schema: str, id_: str, json_data: dict[str, Any]) -> _types.SigilUserUpdateResponse:
        """USER UPDATE — Sugar: update non-credential fields. Equivalent to ENVELOPE UPDATE."""
        args: list[str] = ["USER", "UPDATE"]
        args.append(str(schema))
        args.append(str(id_))
        args.append(json_data if isinstance(json_data, str) else json.dumps(json_data))
        result = await self._transport.execute(self._engine, args)
        return _types.SigilUserUpdateResponse(
            entity_id=result.get("entity_id", ""),
            fields=result.get("fields", None),
            status=result.get("status", ""),
            updated_at=result.get("updated_at", 0),
        )

    async def user_verify(self, schema: str, id_: str, password: str) -> _types.SigilUserVerifyResponse:
        """USER VERIFY — Sugar: verify credential. Infers the credential field from schema. Equivalent to ENVELOPE VERIFY with implicit field."""
        args: list[str] = ["USER", "VERIFY"]
        args.append(str(schema))
        args.append(str(id_))
        args.append(str(password))
        result = await self._transport.execute(self._engine, args)
        return _types.SigilUserVerifyResponse(status=result.get("status", ""), valid=result.get("valid", False))
