# Auto-generated by shroudb-codegen. Do not edit.

from __future__ import annotations

import base64
import json
from typing import Any

from .._transport._interface import Transport
from ..types import stash as _types


class StashNamespace:
    """Stash — Encrypted blob storage with S3 backend and envelope encryption"""

    def __init__(self, transport: Transport, engine: str = "stash") -> None:
        self._transport = transport
        self._engine = engine

    async def command(self) -> dict[str, Any]:
        """COMMAND — List supported commands"""
        args: list[str] = ["COMMAND"]
        result = await self._transport.execute(self._engine, args)
        return result

    async def fingerprint(self, id_: str, viewer_id: str, params: str | None = None) -> _types.StashFingerprintResponse:
        """FINGERPRINT — Create a viewer-specific encrypted copy of a blob for leak tracing"""
        args: list[str] = ["FINGERPRINT"]
        args.append(str(id_))
        args.append(str(viewer_id))
        if params is not None:
            args.append("PARAMS")
            args.append(str(params))
        result = await self._transport.execute(self._engine, args)
        return _types.StashFingerprintResponse(
            created_at=result.get("created_at", 0),
            s3_key=result.get("s3_key", ""),
            status=result.get("status", ""),
            viewer_id=result.get("viewer_id", ""),
        )

    async def health(self) -> dict[str, Any]:
        """HEALTH — Health check"""
        args: list[str] = ["HEALTH"]
        result = await self._transport.execute(self._engine, args)
        return result

    async def inspect(self, id_: str) -> _types.StashInspectResponse:
        """INSPECT — Read blob metadata without downloading or decrypting"""
        args: list[str] = ["INSPECT"]
        args.append(str(id_))
        result = await self._transport.execute(self._engine, args)
        return _types.StashInspectResponse(
            blob_status=result.get("blob_status", ""),
            client_encrypted=result.get("client_encrypted", False),
            content_type=result.get("content_type", ""),
            created_at=result.get("created_at", 0),
            encrypted_size=result.get("encrypted_size", 0),
            id=result.get("id", ""),
            key_version=result.get("key_version", 0),
            keyring=result.get("keyring", ""),
            plaintext_size=result.get("plaintext_size", 0),
            status=result.get("status", ""),
            updated_at=result.get("updated_at", 0),
            viewer_count=result.get("viewer_count", 0),
        )

    async def list(self, limit: int | None = None) -> _types.StashListResponse:
        """LIST — List blobs for the current tenant"""
        args: list[str] = ["LIST"]
        if limit is not None:
            args.append("LIMIT")
            args.append(str(limit))
        result = await self._transport.execute(self._engine, args)
        return _types.StashListResponse(
            blobs=result.get("blobs", None),
            count=result.get("count", 0),
            status=result.get("status", ""),
            tenant=result.get("tenant", ""),
        )

    async def ping(self) -> dict[str, Any]:
        """PING — Ping-pong"""
        args: list[str] = ["PING"]
        result = await self._transport.execute(self._engine, args)
        return result

    async def retrieve(self, id_: str) -> dict[str, Any]:
        """RETRIEVE — Retrieve and decrypt a blob"""
        args: list[str] = ["RETRIEVE"]
        args.append(str(id_))
        result = await self._transport.execute(self._engine, args)
        return result

    async def revoke(self, id_: str, soft: bool = False) -> _types.StashRevokeResponse:
        """REVOKE — Revoke a blob (hard crypto-shred by default, SOFT for soft revoke)"""
        args: list[str] = ["REVOKE"]
        args.append(str(id_))
        if soft:
            args.append("SOFT")
        result = await self._transport.execute(self._engine, args)
        return _types.StashRevokeResponse(
            id=result.get("id", ""),
            revoke_mode=result.get("revoke_mode", ""),
            status=result.get("status", ""),
        )

    async def rewrap(self, id_: str) -> _types.StashRewrapResponse:
        """REWRAP — Re-wrap a blob's DEK under the current Cipher key version. The blob ciphertext is not re-encrypted — only the key wrapping changes."""
        args: list[str] = ["REWRAP"]
        args.append(str(id_))
        result = await self._transport.execute(self._engine, args)
        return _types.StashRewrapResponse(
            id=result.get("id", ""),
            key_version=result.get("key_version", 0),
            status=result.get("status", ""),
            updated_at=result.get("updated_at", 0),
        )

    async def store(self, id_: str, data_b64: str, client_encrypted: str | None = None, content_type: str | None = None, keyring: str | None = None) -> _types.StashStoreResponse:
        """STORE — Store an encrypted blob"""
        args: list[str] = ["STORE"]
        args.append(str(id_))
        args.append(str(data_b64))
        if client_encrypted is not None:
            args.append("CLIENT_ENCRYPTED")
            args.append(str(client_encrypted))
        if content_type is not None:
            args.append("CONTENT_TYPE")
            args.append(str(content_type))
        if keyring is not None:
            args.append("KEYRING")
            args.append(str(keyring))
        result = await self._transport.execute(self._engine, args)
        return _types.StashStoreResponse(
            client_encrypted=result.get("client_encrypted", False),
            content_hash=result.get("content_hash", None),
            deduplicated=result.get("deduplicated", False),
            encrypted_size=result.get("encrypted_size", 0),
            id=result.get("id", ""),
            key_version=result.get("key_version", 0),
            keyring=result.get("keyring", ""),
            plaintext_size=result.get("plaintext_size", 0),
            s3_key=result.get("s3_key", ""),
            status=result.get("status", ""),
        )

    async def trace(self, id_: str) -> _types.StashTraceResponse:
        """TRACE — Return the viewer map (who has copies) for a blob"""
        args: list[str] = ["TRACE"]
        args.append(str(id_))
        result = await self._transport.execute(self._engine, args)
        return _types.StashTraceResponse(
            blob_status=result.get("blob_status", ""),
            id=result.get("id", ""),
            status=result.get("status", ""),
            viewer_count=result.get("viewer_count", 0),
            viewers=result.get("viewers", None),
        )
