# Auto-generated by shroudb-codegen. Do not edit.

from __future__ import annotations

import base64
import json
from typing import Any

from .._transport._interface import Transport
from ..types import veil as _types


class VeilNamespace:
    """Veil — Searchable encryption with blind indexing"""

    def __init__(self, transport: Transport, engine: str = "veil") -> None:
        self._transport = transport
        self._engine = engine

    async def auth(self, token: str) -> _types.VeilAuthResponse:
        """AUTH — Authenticate this connection"""
        args: list[str] = ["AUTH"]
        args.append(str(token))
        result = await self._transport.execute(self._engine, args)
        return _types.VeilAuthResponse(status=result.get("status", None))

    async def command_list(self) -> _types.VeilCommandListResponse:
        """COMMAND LIST — List all supported commands"""
        args: list[str] = ["COMMAND", "LIST"]
        result = await self._transport.execute(self._engine, args)
        return _types.VeilCommandListResponse(count=result.get("count", None), commands=result.get("commands", None))

    async def delete(self, index: str, id_: str) -> _types.VeilDeleteResponse:
        """DELETE — Remove an entry's blind tokens from the index"""
        args: list[str] = ["DELETE"]
        args.append(str(index))
        args.append(str(id_))
        result = await self._transport.execute(self._engine, args)
        return _types.VeilDeleteResponse(status=result.get("status", None), id=result.get("id", None))

    async def health(self) -> _types.VeilHealthResponse:
        """HEALTH — Health check"""
        args: list[str] = ["HEALTH"]
        result = await self._transport.execute(self._engine, args)
        return _types.VeilHealthResponse(status=result.get("status", None))

    async def index_create(self, name: str) -> _types.VeilIndexCreateResponse:
        """INDEX CREATE — Create a new blind index with a fresh HMAC key"""
        args: list[str] = ["INDEX", "CREATE"]
        args.append(str(name))
        result = await self._transport.execute(self._engine, args)
        return _types.VeilIndexCreateResponse(
            status=result.get("status", None),
            index=result.get("index", None),
            created_at=result.get("created_at", None),
            tokenizer_version=result.get("tokenizer_version", None),
        )

    async def index_destroy(self, name: str) -> _types.VeilIndexDestroyResponse:
        """INDEX DESTROY — Crypto-shred an index: zeroize the HMAC key, delete all entries, and remove the index. After destruction, the index name can be reused."""
        args: list[str] = ["INDEX", "DESTROY"]
        args.append(str(name))
        result = await self._transport.execute(self._engine, args)
        return _types.VeilIndexDestroyResponse(
            status=result.get("status", None),
            index=result.get("index", None),
            deleted_entries=result.get("deleted_entries", None),
        )

    async def index_info(self, name: str) -> _types.VeilIndexInfoResponse:
        """INDEX INFO — Get information about a blind index"""
        args: list[str] = ["INDEX", "INFO"]
        args.append(str(name))
        result = await self._transport.execute(self._engine, args)
        return _types.VeilIndexInfoResponse(
            index=result.get("index", None),
            created_at=result.get("created_at", None),
            entry_count=result.get("entry_count", None),
            tokenizer_version=result.get("tokenizer_version", None),
        )

    async def index_list(self) -> _types.VeilIndexListResponse:
        """INDEX LIST — List all blind index names"""
        args: list[str] = ["INDEX", "LIST"]
        result = await self._transport.execute(self._engine, args)
        return _types.VeilIndexListResponse(items=result.get("items", ""), type=result.get("type", None))

    async def index_reconcile(self, name: str, valid_ids: str) -> _types.VeilIndexReconcileResponse:
        """INDEX RECONCILE — Remove orphaned entries from the index. Compares stored entry IDs against the provided valid set and deletes any entries not in the set."""
        args: list[str] = ["INDEX", "RECONCILE"]
        args.append(str(name))
        args.append(str(valid_ids))
        result = await self._transport.execute(self._engine, args)
        return _types.VeilIndexReconcileResponse(
            status=result.get("status", None),
            index=result.get("index", None),
            orphans_removed=result.get("orphans_removed", None),
        )

    async def index_reindex(self, name: str) -> _types.VeilIndexReindexResponse:
        """INDEX REINDEX — Clear all entries and update the tokenizer version to current. The HMAC key is preserved. After reindex, the application must re-submit all entries via PUT. Use this when the tokenizer algorithm has been upgraded."""
        args: list[str] = ["INDEX", "REINDEX"]
        args.append(str(name))
        result = await self._transport.execute(self._engine, args)
        return _types.VeilIndexReindexResponse(
            status=result.get("status", None),
            index=result.get("index", None),
            tokenizer_version=result.get("tokenizer_version", None),
            entries_cleared=result.get("entries_cleared", None),
        )

    async def index_rotate(self, name: str) -> _types.VeilIndexRotateResponse:
        """INDEX ROTATE — Rotate an index's HMAC key. Generates a new key, deletes all existing entries. The application must re-index all entries after rotation."""
        args: list[str] = ["INDEX", "ROTATE"]
        args.append(str(name))
        result = await self._transport.execute(self._engine, args)
        return _types.VeilIndexRotateResponse(
            status=result.get("status", None),
            index=result.get("index", None),
            rotated_at=result.get("rotated_at", None),
            entry_count=result.get("entry_count", None),
        )

    async def ping(self) -> _types.VeilPingResponse:
        """PING — Ping-pong"""
        args: list[str] = ["PING"]
        result = await self._transport.execute(self._engine, args)
        return _types.VeilPingResponse(type=result.get("type", ""), value=result.get("value", None))

    async def put(self, index: str, id_: str, data_b64: str, field: str | None = None, blind: bool = False) -> _types.VeilPutResponse:
        """PUT — Store blind tokens for an entry. In standard mode, data_b64 is base64-encoded plaintext (server tokenizes). With BLIND flag, data_b64 is base64-encoded BlindTokenSet JSON (client pre-tokenized, for E2EE)."""
        args: list[str] = ["PUT"]
        args.append(str(index))
        args.append(str(id_))
        args.append(str(data_b64))
        if field is not None:
            args.append("FIELD")
            args.append(str(field))
        if blind:
            args.append("BLIND")
        result = await self._transport.execute(self._engine, args)
        return _types.VeilPutResponse(
            status=result.get("status", None),
            id=result.get("id", None),
            version=result.get("version", None),
        )

    async def search(self, index: str, query: str, mode: str | None = None, field: str | None = None, limit: int | None = None, blind: bool = False) -> _types.VeilSearchResponse:
        """SEARCH — Search a blind index. In standard mode, query is plain text (server tokenizes). With BLIND flag, query is base64-encoded BlindTokenSet JSON (client pre-tokenized, for E2EE)."""
        args: list[str] = ["SEARCH"]
        args.append(str(index))
        args.append(str(query))
        if mode is not None:
            args.append("MODE")
            args.append(str(mode))
        if field is not None:
            args.append("FIELD")
            args.append(str(field))
        if limit is not None:
            args.append("LIMIT")
            args.append(str(limit))
        if blind:
            args.append("BLIND")
        result = await self._transport.execute(self._engine, args)
        return _types.VeilSearchResponse(
            status=result.get("status", None),
            scanned=result.get("scanned", None),
            matched=result.get("matched", None),
            results=result.get("results", None),
        )

    async def tokenize(self, index: str, plaintext_b64: str, field: str | None = None) -> _types.VeilTokenizeResponse:
        """TOKENIZE — Generate blind tokens from plaintext without storing. Returns HMAC-derived tokens for external use."""
        args: list[str] = ["TOKENIZE"]
        args.append(str(index))
        args.append(str(plaintext_b64))
        if field is not None:
            args.append("FIELD")
            args.append(str(field))
        result = await self._transport.execute(self._engine, args)
        return _types.VeilTokenizeResponse(
            status=result.get("status", None),
            words=result.get("words", None),
            trigrams=result.get("trigrams", None),
            tokens=result.get("tokens", None),
        )
